### ISSUE TITLE
Outgoing webhook sends several requests in a row

### ISSUE THREAD

**Issue by viktor-shmigol** [MicrosoftDocs/msteams-docs#11424]
### Type of issue

Feature doesn't work (bug)

### Feedback

Hello,

We are encountering an issue with multiple POST requests being sent to our API.

We created an outgoing webhook in our team, and when we mention this webhook (e.g., @Teams Test 1 test message), it triggers 3 or more identical messages to our API.

Please see the example below:
![image](https://github.com/user-attachments/assets/e4490663-e5a9-4a33-84fb-ebe38f5bd813)

We tested it using the Node.js example from this repository: [Microsoft Teams Samples - Outgoing Webhook (Node.js)](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/outgoing-webhook/nodejs).  This example is suggested by the following article: [Add an outgoing webhook](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook?tabs=urljsonpayload%2Cdotnet).

Additionally, we tested it using a simple Ruby Grape API and encountered the same issue. The Teams outgoing webhook is being sent to our API multiple times.
```
class API::V1::IncomingWebhooks::Messages < Grape::API

  format :json

  helpers do

    def request_hmac_signature

      request.headers['authorization'].to_s.split[1]

    end

    def valid_hmac?

      serialized_payload_bytes = request.body.read.encode('utf-8')

      key_bytes = Base64.decode64(ENV['TEAMS_SECRET'])

      hmac_sha256 = OpenSSL::HMAC.digest('sha256', key_bytes, serialized_payload_bytes)

      calculated_hmac_value = Base64.encode64(hmac_sha256).strip

      request_hmac_signature == calculated_hmac_value

    end

  end

  namespace 'incoming_webhooks/:id' do

    resources :messages do

      desc 'Creates message'

      post do

        return unauthorized! unless valid_hmac?

        { type: 'message', text: 'Successfully received' }

      end

    end

  end

end
```

The result is the same
![image](https://github.com/user-attachments/assets/d2819682-3c4a-428d-8080-2982409a8653)

Is there any solution to fix it?

Thanks!

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook?tabs=urljsonpayload%2Cdotnet

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md

### Author

@surbhigupta

### Document Id

43e90995-bba4-86b6-1f1c-ab749e546a4b

**Comment by sayali-MSFT** [comment]
@viktor-shmigol - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@viktor-shmigol -We have tried the above scenario on both web and desktop clients, and it is working fine on our end.
Could you please check it with the Teams version listed below?
Microsoft Teams version 24215.1000.3037.6292. 
The client version is 49/24061318413.

![image](https://github.com/user-attachments/assets/e1f26ec0-c99b-4201-b7c7-c44210c17d86)

**Comment by viktor-shmigol** [comment]
@sayali-MSFT Hello,
I've tested it in WEB https://teams.microsoft.com/v2/ and desktop app on Mac OS Version 24193.1707.3028.4282 (24193.1707.3028.4282) .

If I try to mention and send a message in both apps in the channel to the outgoing webhook, the teams will send double or more requests to our API.
Note: Our API returns status 201 and following json: 
```
{ "type:": "message", "text": "Successfully received" }
```
See the movies app below:

Desktop:
https://github.com/user-attachments/assets/4579979f-6380-4663-8f6c-8e61ebccf0f5

WEB:

https://github.com/user-attachments/assets/233048d2-05c2-47bb-af04-03e28aaa9653



Installed apps in the team:
<img width="1002" alt="Screenshot 2024-08-07 at 18 33 41" src="https://github.com/user-attachments/assets/bed2ad72-0da6-403d-b97c-197e5228fb5a">

**Comment by sayali-MSFT** [comment]
@viktor-shmigol -We will test this issue on a Mac device and let you know the update. We have tested it on a Windows device, and it is working fine there.

**Comment by viktor-shmigol** [comment]
@sayali-MSFT I tested it in WEB/Desktop in Windows as well. I'm getting the same bug.

**Comment by sayali-MSFT** [comment]
@viktor-shmigol -Could you please share the client version?

Have you test this with the below version?

Microsoft Teams version 24215.1000.3037.6292.
The client version is 49/24061318413.

**Comment by viktor-shmigol** [comment]
@sayali-MSFT The desktop version is 24193.1707.3028.4282 (24193.1707.3028.4282)
The client version is 1415/24062724817.

I've just upgraded the WEB. The issue is still present.
<img width="955" alt="Screenshot 2024-08-08 at 13 49 43" src="https://github.com/user-attachments/assets/65c44716-30dd-4d90-b2e6-ffd870162ab6">

**Comment by viktor-shmigol** [comment]
@sayali-MSFT I do not know what you did but it stopped sending double posts. Thank you!
<img width="504" alt="Screenshot 2024-08-08 at 13 59 43" src="https://github.com/user-attachments/assets/3eccc58d-7334-465a-9815-35aea7270200">

**Comment by sayali-MSFT** [comment]
@viktor-shmigol - Glad to hear that your issue is resolved.

Could you please share your valuable feedback via Microsoft Teams Developer Feedback link.
https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u

**Comment by viktor-shmigol** [comment]
@sayali-MSFT I'm sorry. it still sending double posts. There was some glitch. It's not resolved yet.
<img width="1267" alt="Screenshot 2024-08-08 at 14 02 25" src="https://github.com/user-attachments/assets/38c35e6e-ea02-4daf-becd-b1679a68003e">

**Comment by sayali-MSFT** [comment]
Could you please share error logs so that we can investigate from our end?

**Comment by viktor-shmigol** [comment]
@sayali-MSFT Here is the logs from API. As you can see the API recieved two requests with interval in one second.

```
2024-08-08T13:44:17.163832645Z app[web.1]: 172.17.0.1 - - [08/Aug/2024:13:44:17 +0000] "POST /api/v2/incoming_webhooks/4fc47565-955f-4ad6-86b2-e942811b3db8/microsoft_teams/messages HTTP/1.1" 201 60 "https://teams.microsoft.com/" "-"
2024-08-08T13:44:18.377968879Z app[web.1]: 172.17.0.1 - - [08/Aug/2024:13:44:18 +0000] "POST /api/v2/incoming_webhooks/4fc47565-955f-4ad6-86b2-e942811b3db8/microsoft_teams/messages HTTP/1.1" 201 60 "https://teams.microsoft.com/" "-"
```

Also, I'm receiving these errors while receiving reply messages from Webhook in WEB app. As you can see I'm receiving two JS records as well.
<img width="1351" alt="Screenshot 2024-08-08 at 16 51 43" src="https://github.com/user-attachments/assets/cef033f6-4db7-4666-b7f8-1330ece01a0a">

```
v2/:1 Access to fetch at 'https://urlp.asm.skype.com/v1/url/content?url=https%3A%2F%2Fres.cdn.office.net%2Fteamsappdata%2Fevergreen-assets%2Fapps%2Foutcomingwebhook_largeimage.png&v=1' from origin 'https://teams.microsoft.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
async-entry-a009e2428bc2c2a4.js:43 
        
        
       GET https://urlp.asm.skype.com/v1/url/content?url=https%3A%2F%2Fres.cdn.office.net%2Fteamsappdata%2Fevergreen-assets%2Fapps%2Foutcomingwebhook_largeimage.png&v=1 net::ERR_FAILED
nR @ async-entry-a009e2428bc2c2a4.js:43
(anonymous) @ async-entry-a009e2428bc2c2a4.js:43
(anonymous) @ async-entry-a009e2428bc2c2a4.js:43
(anonymous) @ async-entry-a009e2428bc2c2a4.js:43
(anonymous) @ async-entry-a009e2428bc2c2a4.js:43
(anonymous) @ async-entry-a009e2428bc2c2a4.js:43
await in (anonymous)
(anonymous) @ async-entry-a009e2428bc2c2a4.js:43
(anonymous) @ async-entry-a009e2428bc2c2a4.js:43
(anonymous) @ async-entry-a009e2428bc2c2a4.js:43
await in (anonymous)
getImageAsDataUri @ services-toast-image-328dfca659f19d98.js:1
toastImageAsDataUri @ r_data-resolvers-toast-85f6fa3766e334cc.js:1
await in toastImageAsDataUri
Ie @ 552520-4ca55c4a2f58170e.js:1
he @ 552520-4ca55c4a2f58170e.js:1
pe @ 552520-4ca55c4a2f58170e.js:1
(anonymous) @ 552520-4ca55c4a2f58170e.js:1
fe @ 552520-4ca55c4a2f58170e.js:1
(anonymous) @ supermassive-incremental-link-198b87ba581865c6.js:1
Promise.then
(anonymous) @ supermassive-incremental-link-198b87ba581865c6.js:1
(anonymous) @ data-view-schema-d7889a531a8fa089.js:1
e @ 548427-50836f59a12e2130.js:1
(anonymous) @ 548427-50836f59a12e2130.js:1
(anonymous) @ async-entry-a009e2428bc2c2a4.js:30
Promise.then
(anonymous) @ async-entry-a009e2428bc2c2a4.js:30
e @ 548427-50836f59a12e2130.js:1
(anonymous) @ 548427-50836f59a12e2130.js:1
(anonymous) @ 548427-50836f59a12e2130.js:1
e @ 548427-50836f59a12e2130.js:1
(anonymous) @ 548427-50836f59a12e2130.js:1
complete @ 548427-50836f59a12e2130.js:1
(anonymous) @ 548427-50836f59a12e2130.js:1
t @ 548427-50836f59a12e2130.js:1
(anonymous) @ 548427-50836f59a12e2130.js:1
(anonymous) @ 548427-50836f59a12e2130.js:1
_ @ 548427-50836f59a12e2130.js:1
(anonymous) @ 548427-50836f59a12e2130.js:1
E @ 548427-50836f59a12e2130.js:1
(anonymous) @ 548427-50836f59a12e2130.js:1
(anonymous) @ 548427-50836f59a12e2130.js:1
(anonymous) @ 548427-50836f59a12e2130.js:1
(anonymous) @ 548427-50836f59a12e2130.js:1
(anonymous) @ 548427-50836f59a12e2130.js:1
query @ async-entry-a009e2428bc2c2a4.js:30
nhe @ async-entry-a009e2428bc2c2a4.js:43
await in nhe
rhe @ async-entry-a009e2428bc2c2a4.js:43
(anonymous) @ async-entry-a009e2428bc2c2a4.js:43
b @ 548427-50836f59a12e2130.js:1
E @ 548427-50836f59a12e2130.js:1
(anonymous) @ 548427-50836f59a12e2130.js:1
next @ 548427-50836f59a12e2130.js:1
b @ 548427-50836f59a12e2130.js:1
E @ 548427-50836f59a12e2130.js:1
(anonymous) @ 548427-50836f59a12e2130.js:1
next @ 548427-50836f59a12e2130.js:1
b @ 548427-50836f59a12e2130.js:1
E @ 548427-50836f59a12e2130.js:1
(anonymous) @ 548427-50836f59a12e2130.js:1
(anonymous) @ 548427-50836f59a12e2130.js:1
F @ 548427-50836f59a12e2130.js:1
next @ 548427-50836f59a12e2130.js:1
b @ 548427-50836f59a12e2130.js:1
E @ 548427-50836f59a12e2130.js:1
(anonymous) @ 548427-50836f59a12e2130.js:1
next @ async-entry-a009e2428bc2c2a4.js:30
b @ 548427-50836f59a12e2130.js:1
E @ 548427-50836f59a12e2130.js:1
(anonymous) @ 548427-50836f59a12e2130.js:1
next @ 548427-50836f59a12e2130.js:1
_ @ 548427-50836f59a12e2130.js:1
m @ 548427-50836f59a12e2130.js:1
value @ 548427-50836f59a12e2130.js:1
(anonymous) @ async-entry-a009e2428bc2c2a4.js:30
onNext @ async-entry-a009e2428bc2c2a4.js:30
onSuccess @ async-entry-a009e2428bc2c2a4.js:30
onSuccess @ async-entry-a009e2428bc2c2a4.js:30
setResponseAndEndScenario @ async-entry-a009e2428bc2c2a4.js:30
reconcileResponse @ async-entry-a009e2428bc2c2a4.js:30
onMessageReceived @ async-entry-a009e2428bc2c2a4.js:30
Iv.onResponseReceived @ async-entry-a009e2428bc2c2a4.js:30
handleResponse @ async-entry-a009e2428bc2c2a4.js:30
handleResponse @ async-entry-a009e2428bc2c2a4.js:30
onMessageCallback @ async-entry-a009e2428bc2c2a4.js:30
(anonymous) @ async-entry-a009e2428bc2c2a4.js:30
d.onmessage @ async-entry-a009e2428bc2c2a4.js:30
v2/:6 Unhandled error/rejection {"isTrusted":true}
```

**Comment by sayali-MSFT** [comment]
These logs show that two POST requests to the same endpoint were made, and both were successful (HTTP status 201). If this behavior is unexpected, you might want to:

1. **Check for Duplicate Requests**: Ensure that the sender is not retrying or sending duplicate requests unintentionally.
2. **Review Webhook Configuration**: Verify that the webhook is correctly configured and that no duplicate webhooks are set up.
3. **Inspect Request Payloads**: Check if the payloads of the two requests are identical or if there is any difference.

Also try the below attached sample, just change the sharedSecret in app.js file.
[nodejs.zip](https://github.com/user-attachments/files/16580995/nodejs.zip)

**Comment by sayali-MSFT** [comment]
@viktor-shmigol -We have tested this scenario again, and it is working fine on both web and desktop. 
The client version is 1415/24081700411.
![image](https://github.com/user-attachments/assets/15e40461-6bac-4910-b047-7e90be02c033)




We are checking your issue with the engineering team and will let you know the update.

**Comment by viktor-shmigol** [comment]
@sayali-MSFT We are still having this issue. Were you able to test this issue with DEV team.
Thanks!

**Comment by sayali-MSFT** [comment]
@viktor-shmigol -We have tested this issue on Web and Desktop client as well. 

You have Microsoft Teams version 24231.512.3106.6573.
The client version is 49/24081700413.

**Comment by viktor-shmigol** [comment]
@sayali-MSFT Did they debug backend part of their side using my log?(See screenhsot bellow).
Should I provide something else? Maybe I need to return some specific json OR inject some header?
```
{ "type": "message", text: "Successfully received" }
``` 

I'm asking as we cannot resolve double post issue. We tested it in different ways with our API and demo nodejs API: https://github.com/MicrosoftDocs/msteams-docs/issues/11424#issuecomment-2283743674 .
The teams API sends it twice or more times. We tried to remove channel, team and outgoing webhooks, nothing helps.
We are using different platforms such as WEB, desctop, but we are having the same issue.

<img width="1342" alt="1" src="https://github.com/user-attachments/assets/4b871b6a-2e8d-4f69-8794-0d403fd78529">

**Comment by sayali-MSFT** [comment]
> @sayali-MSFT Did they debug backend part of their side using my log?(See screenhsot bellow). Should I provide something else? Maybe I need to return some specific json OR inject some header?
> 
> ```
> { "type": "message", text: "Successfully received" }
> ```
> 
> I'm asking as we cannot resolve double post issue. We tested it in different ways with our API and demo nodejs API: [#11424 (comment)](https://github.com/MicrosoftDocs/msteams-docs/issues/11424#issuecomment-2283743674) . The teams API sends it twice or more times. We tried to remove channel, team and outgoing webhooks, nothing helps. We are using different platforms such as WEB, desctop, but we are having the same issue.
> 
> <img alt="1" width="1342" src="https://private-user-images.githubusercontent.com/8638674/365627764-4b871b6a-2e8d-4f69-8794-0d403fd78529.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODE4OTMsIm5iZiI6MTcyNTg4MTU5MywicGF0aCI6Ii84NjM4Njc0LzM2NTYyNzc2NC00Yjg3MWI2YS0yZThkLTRmNjktODc5NC0wZDQwM2ZkNzg1MjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDlUMTEzMzEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzNmY2QzNGZiOWYyZTA3MWZhZjJiMzMxODc4ZjQ0N2Q0ZjE0Mzg3ZDMxZmI2YTQzNWRlNGI5ZDc4OWEwYTViMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yUfyMxFbD0RWf_vsSPtVsreujNLrIsXp3AsszqySPvU">

We are checking your issue with the engineering team and will let you know the update.

**Comment by viktor-shmigol** [comment]
got it

**Comment by viktor-shmigol** [comment]
@sayali-MSFT Sorry, but I've tested outgoing webhooks with that sample multiple times. I told about it.
It also receives double posts!. Let me know If you need to provide with more details.

**Comment by sayali-MSFT** [comment]
@viktor-shmigol -Can we get network capture when the user at mentions the Outgoing webhook bot in Teams?

**Comment by viktor-shmigol** [comment]
@sayali-MSFT Here is the messages payload:

```
{
  "id": "-1",
  "type": "Message",
  "conversationid": "19:VIK4fAKZBU8w1fop1aC7mCT6lPXXLZzY0kOA9-9aFBo1@thread.tacv2",
  "conversationLink": "blah/19:VIK4fAKZBU8w1fop1aC7mCT6lPXXLZzY0kOA9-9aFBo1@thread.tacv2",
  "from": "8:orgid:55ffdb24-452a-43c8-b7d2-da6e2693c956",
  "composetime": "2024-09-13T12:17:16.503Z",
  "originalarrivaltime": "2024-09-13T12:17:16.503Z",
  "content": "<p><readonly class=\"skipProofing\" contenteditable=\"false\" spellcheck=\"false\" itemtype=\"http://schema.skype.com/Mention\"><span itemtype=\"http://schema.skype.com/Mention\" itemscope itemid=\"0\">Test</span></readonly>&nbsp;<readonly class=\"skipProofing\" contenteditable=\"false\" spellcheck=\"false\" itemtype=\"http://schema.skype.com/Mention\"><span itemtype=\"http://schema.skype.com/Mention\" itemscope itemid=\"2\">webhook</span></readonly>&nbsp;Hello world</p>",
  "messagetype": "RichText/Html",
  "contenttype": "Text",
  "imdisplayname": "Viktor Shmigol",
  "clientmessageid": "7463643863206225656",
  "callId": "",
  "state": 0,
  "version": "0",
  "amsreferences": [],
  "properties": {
    "importance": "",
    "subject": "",
    "title": "",
    "cards": "[]",
    "links": "[]",
    "mentions": "[{\"@type\":\"http://schema.skype.com/Mention\",\"itemid\":\"1\",\"mri\":\"28:22e50a9b-80cc-4eab-a092-ce64796d28d7\",\"mentionType\":\"webhook\",\"displayName\":\"Test\"},{\"@type\":\"http://schema.skype.com/Mention\",\"itemid\":\"3\",\"mri\":\"28:22e50a9b-80cc-4eab-a092-ce64796d28d7\",\"mentionType\":\"webhook\",\"displayName\":\"webhook\"}]",
    "onbehalfof": "[{\"itemid\":\"0\",\"mri\":\"00f578f9-393a-4390-a470-5dfb8a3acab4\",\"mentionType\":\"webhook\",\"displayName\":\"Test\"},{\"itemid\":\"2\",\"mri\":\"00f578f9-393a-4390-a470-5dfb8a3acab4\",\"mentionType\":\"webhook\",\"displayName\":\"webhook\"}]",
    "files": "[]",
    "policyViolation": null
  },
  "postType": "Standard",
  "crossPostChannels": []
}

**Comment by sayali-MSFT** [comment]
@viktor-shmigol -Thanks for sharing the details. We will provide this to the engineering team and let you know the updates.

**Comment by sayali-MSFT** [comment]
@viktor-shmigol - The engineering team is also unable to reproduce the issue. 
For further investigation, they need a network or HAR capture from your end, as this will provide the necessary headers to trace the logs effectively. Please generate the HAR file during the reproduction of the issue and share it with us. This will help us identify the root cause more efficiently.

 Thank you!

**Comment by evitecjussi** [comment]
Ran across this while looking for info on another Teams related issue. We've had the same problem, and it's because Teams for some reason treats each space separated part of the name as a separate mention. So in your first screenshot you're mentioning **Teams Test 1**, so Teams sends three requests: one for **Teams**, another one for **Test** and a third one for **1**. Meanwhile the engineering team has been testing with **Webhook_Outgoing** - no space, so it counts as a single mention.

It's very unintuitive behavior, but the easy workaround is to simply remove the spaces from your webhook name.

**Comment by alexandredavi** [comment]
I'm having this issue. The @evitecjussi workaround worked.
