### ISSUE TITLE
Out of office message not shown in mobile app

### ISSUE THREAD

**Issue by GabrielSandor** [MicrosoftDocs/msteams-docs#1372]
The mobile app only shows the out-of-office status of a co-worker, and not the message, which might contain important information such as the leave duration and the escalation contact.

**Comment by Gousia-MSFT** [comment]
@GabrielSandor You can see the OOF message of the user when you click on the name of the user from the chat.
![image](https://user-images.githubusercontent.com/45553518/74811546-b557ba00-5317-11ea-8ba4-2d3d31d0aec1.png)

**Comment by GabrielSandor** [comment]
Hello @Gousia-MSFT,

I don't see this in the iOS mobile app.

**Comment by Gousia-MSFT** [comment]
@GabrielSandor I checked this internally and seems like everything works well in iOS as well. OOF messages may take a while to propagate from Outlook to Teams which is probably why when you checked, it was not there yet. Could you please try this sometime after setting the OOF message and check if you could see it?

**Comment by GabrielSandor** [comment]
@Gousia-MSFT I just checked for a colleague that set her status to out-of-office last week, and the iOS app still doesn't show the out-of-office message, only the status. If it's a synchronization delay, why is it taking so long?

**Comment by Gousia-MSFT** [comment]
@GabrielSandor We could not repro the issue on our side.
![image](https://user-images.githubusercontent.com/45553518/75759201-31f88880-5d5b-11ea-9bd2-bdced5d8e975.png)
Could you please try updating the Teams client version?

**Comment by GabrielSandor** [comment]
@Gousia-MSFT The screenshot you're showing is from the Android app, isn't it? I'm referring to the iOS/Apple mobile application.

I have the latest version of the iOS app, 2.0.2. At least i believe it's the latest, App Store should keep the apps up-to-date automatically.

**Comment by Gousia-MSFT** [comment]
@GabrielSandor This screenshot is from iOS app. Could you please share a screenshot of what you see on the iOS app?

**Comment by GabrielSandor** [comment]
@Gousia-MSFT it seems we have different versions of iOS, but i hope this doesn't make a difference to the Teams app.

Here is a screenshot:

![ooo](https://user-images.githubusercontent.com/3800303/75762170-e803a880-5d42-11ea-9c55-7927aa1315ff.png)

**Comment by Gousia-MSFT** [comment]
Thanks for sharing the screenshot. We are looking into this.

**Comment by Gousia-MSFT** [comment]
@GabrielSandor This issue has been fixed with the latest release. Could you please check and confirm?

**Comment by GabrielSandor** [comment]
@Gousia-MSFT i updated to version 2.0.4 and i still don't see the out of office extended message.

**Comment by Gousia-MSFT** [comment]
@GabrielSandor I just checked with the team. It looks like the release with the fix is not out yet. Hopefully it will be out soon but we do not have a firm ETA for this.

**Comment by Gousia-MSFT** [comment]
@GabrielSandor Could you please try sign out and sign in back and see if that fixes the issue?

**Comment by GabrielSandor** [comment]
@Gousia-MSFT i updated MS Teams to the latest version (2.0.6), signed out and in again, but i still don't see the out of office message.

**Comment by Gousia-MSFT** [comment]
@GabrielSandor We can not repro the issue on our side with any build of Teams app on iOS. Could you please confirm if the user set a OOF message or only OOF status.

**Comment by GabrielSandor** [comment]
@Gousia-MSFT I am absolutely sure that the user in question has both an OOF status and a message. See the screenshot in the desktop app for the same user i attached a mobile screenshot above:

![image](https://user-images.githubusercontent.com/3800303/79196418-bea56480-7e38-11ea-9555-ce1f1de149e0.png)

**Comment by Gousia-MSFT** [comment]
@GabrielSandor We cannot repro the issue on our side in any version of the app. Could you please report an issue from the Settings menu in the app. That will also give us some tenant & user details to check further.

**Comment by GabrielSandor** [comment]
@Gousia-MSFT i sent my device details as instructed, let me know if you can't locate the email.

**Comment by Gousia-MSFT** [comment]
@GabrielSandor Thankyou for sharing the details. Our team will look at it.
