### ISSUE TITLE
Administrator has disabled chat for this user spreads to other chat windows

### ISSUE THREAD

**Issue by ttlnd** [MicrosoftDocs/msteams-docs#1449]
If a user that previously had disabled chat but now are available to chat starts chatting with you, the message

> Administrator has disabled chat for this user 

spreads to other chat windows and makes replying to other people disabled as well.

(by opening that chat window as a starting point)

It wasn't this user that was disabled before in the picture below. The only way to make it disappear is to click around in the other chat windows and then switch back to the chat window. Then the message disappears and you can chat again
![image](https://user-images.githubusercontent.com/11815091/76834342-4e052b00-682d-11ea-8a0b-487e76ded550.png)

You have Microsoft Teams Version 1.3.00.3564 (64-bit). It was last updated on 3/2/20.

**Comment by Gousia-MSFT** [comment]
@ttlnd Thanks for reaching out to us. We are looking into this.

**Comment by Gousia-MSFT** [comment]
@ttlnd This has been fixed. Could you please check and confirm if it's fixed for you?

**Comment by Gousia-MSFT** [comment]
Please reopen if you still have the issue.

**Comment by orion3311** [comment]
I am still having this problem. I have a small group of users who policy had disabled chat. I re-enabled them, and now even moved to a new policy, and users still show disabled. If a user chats to me, I can use the pop-up toast to reply to them, despite the normal chat box being "Disabled".

Had users log out/in, cleared entire Teams appdata/cache on both ends, etc.

**Comment by MKCPC** [comment]
I am getting this same issue too and I cant find a resolution.  One thing I haven noticed is if I visit the web version https://teams.microsoft.com I am able to reply to these users.
