### ISSUE TITLE
Call disconnects on answering

### ISSUE THREAD

**Issue by alirezarahimifarid** [MicrosoftDocs/msteams-docs#1623]
After updating the Microsoft Teams Apps on iOS I can't answer ay calls on my Microsoft Teams Apps on my PC. 
As soon as I log off from iOS version (2.0.9) I was able to answer the calls. 
This issue started 5/5/2020 right after I update my Teams App on my cellphone.
Please check this link:
https://techcommunity.microsoft.com/t5/microsoft-teams/call-disconnects-on-answering/m-p/1362405#

**Comment by callworthp** [comment]
We too are seeing this issue. We have found that if we sign out of the iOS app, remove the app, re-install the app from the App Store and log back in the problem is solved. At that point we can stay signed into the app in all locations and calls are answered as expected without issue.

**Comment by Trinetra-MSFT** [comment]
@alirezarahimifarid , You can try the solution suggested by @callworthp. Let me know if you need any further assistance on this.

**Comment by alirezarahimifarid** [comment]
It worked for me but as you can see the response in this post, other people still have the same issue even after reinstalling the app. I can see the Service Health item in Admin Center now.[https://techcommunity.microsoft.com/t5/microsoft-teams/call-disconnects-on-answering/m-p/1366193#M57156](url)
![Teams 2 0 9](https://user-images.githubusercontent.com/12750491/81286598-2acd4f80-9016-11ea-8e5e-d587445e7b0f.JPG)

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you have further queries
