### ISSUE TITLE
Task Module not working in some mobile devices

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/msteams-docs#1969]
[migrated from Bot Framework Samples repository here: https://github.com/microsoft/BotBuilder-Samples/issues/2665]

## Sample information
teams-task-module
Node JS
Bot Framework

## Describe the bug
I am trying  play some video content inside a teams bot using task module. it works fine in desktop but in some Mobile devices it showing error "Failed to load webview". 

##Error Screenshot :-
![taskModule_mobile_error](https://user-images.githubusercontent.com/10558023/89895226-10000d80-dbf9-11ea-8e7e-3e733c28faa9.png)

## Here is list of mobile devices giving  "Failed to load webview" error

1. Samsung On 7 Prime, Android Version 9
2. Pixel XL, Android Version 10
3. Samsung M21, Android Version 10

## To Reproduce
1. Implement task module with adaptive cards

here is code i have written for task module in my adaptive card

actions:[
{
        "type": "Action.Submit",
        "title": title,
        "data": {
         "url" : url,
          "msteams": {
               "type": "task/fetch",
                "title": title,
            }
         }
  } 
]

Server Code :- 

if (turnContext._activity.type === "invoke") {
          let { url } = turnContext._activity.value.data
          res.send({
            task: {
              type: 'continue',
              value: {
                "height": "large",
                "width": "large",
                "url": url
              }
            }
          })

## Expected behavior
it should work like below screenshot
![taskmodule_mobile](https://user-images.githubusercontent.com/10558023/89893779-9bc46a80-dbf6-11ea-97a1-91a6dd3f3ef0.png)

**Comment by Nikitha-MSFT** [comment]
We could able to reproduce the issue. Raised a bug.

**Comment by Nikitha-MSFT** [comment]
Bug is Resolved now, we have tested this at our end, could you please also check and confirm?
The issue is with the Teams client which is fixed now

**Comment by shoryacr7** [comment]
Still getting this issue on Android version 10, Mobile device - One plus 7T. The task module works well in Browser, Microsoft teams desktop version, ios mobile device. The error is same. We are displaying a html page with a form on task module. Rendering an adaptive card instead of html does not cause this issue.
![Screenshot_20210108-132820~2](https://user-images.githubusercontent.com/39670026/103989285-7e032d80-51b5-11eb-89fd-89befa84ae13.jpg)

**Comment by Nikitha-MSFT** [comment]
Could you please check with the latest version?

**Comment by shoryacr7** [comment]
> Could you please check with the latest version?

It works now after updating, should have checked, needed to clear cache and data. Thank you for the prompt reply.

**Comment by aklaw09** [comment]
I'm still facing this issue on Android 10 (Samsung A20). Using the latest version from the google app store. Any possible solution?

**Comment by Wajeed-msft** [comment]
> I'm still facing this issue on Android 10 (Samsung A20). Using the latest version from the google app store. Any possible solution?

Is this failing only for you or anyone else in your team with Android device also facing the same?

**Comment by aklaw09** [comment]
It doesn't work on Android 9 too. It says 'failed to load webview'. It works properly on desktop app though

**Comment by Wajeed-msft** [comment]
@aklaw09 - In order to isolate the issue, could you please confirm if same app works fine for anyone else on mobile?

**Comment by aklaw09** [comment]
The app doesn't work for any of my team members. No known working model to my knowledge.

**Comment by Wajeed-msft** [comment]
Could you please try to install [TaskModuleCSharp.zip](https://github.com/MicrosoftDocs/msteams-docs/files/6815205/TaskModuleCSharp.5.zip) manifest and confirm if you are getting the same errors?

**Comment by aklaw09** [comment]
It works with the above manifest

**Comment by Wajeed-msft** [comment]
Thanks @aklaw09 for confirmation that feature is working fine. Is it possible that same app was installed and uninstalled mutliple time in different scoped (personal, team)? Could you please uninstall all the instances for older apps and try again? 
If you could shared the app manifest along with repor steps, I'll try it at my end once.

**Comment by aklaw09** [comment]
Hi, sorry the late response. The app was installed on multiple counts, but it was restricted to personal scope only. Uninstalled it to no luck. Replacing the bot in the same manifest with the C# one from the above manifest resolves the issue. Cannot share the manifest unfortunately. 

I respond to taskModuleFetch as below

`response = <TaskModuleResponse>{
          task: {
            type: "continue",
            value: <TaskModuleTaskInfo>{
              title: "Title",
              url: "someUrl",
              fallbackUrl:
                "someUrl",
            },
          },
        };
        return Promise.resolve(response);`

**Comment by Wajeed-msft** [comment]
Given that app is working fine once the App Id in manifest file is changed, this doesn't look like code related issue. Most probably this is happening because of having some other manifest (may be in other scope) overriding manifest values. Could you please try [clearning cache and data](https://github.com/MicrosoftDocs/msteams-docs/issues/1969#issuecomment-756656698) once as mentioned by another user?

**Comment by aklaw09** [comment]
Hi. Tried clearing cache and data but the issue still persisted. Even with a fresh manifest connect to a local task module bot gave the same problem
