### ISSUE TITLE
Mentions don't display properly in Android

### ISSUE THREAD

**Issue by SeanFBrampton** [MicrosoftDocs/msteams-docs#1983]
When creating my own adaptive card in Power Automate and attempting to use an @mention, the adaptive card does not call the correct name in Android, rather uses the fallback mention title.

There is no issue on desktop. web or iOS

Original post on Power Automate community [link here](https://powerusers.microsoft.com/t5/Building-Flows/Teams-Adaptive-Card-Mentions/m-p/653064#M87477)

Please let me know if you need more information.

**Comment by VaraPrasad-MSFT** [comment]
This is a know issue, we have active bug. We don't have ETA to share when it will be fixed.

**Comment by SeanFBrampton** [comment]
Hello, is there an update on this?  This bug is still present and is impeding our ability to use mentions across our Corporation.

**Comment by SeanFBrampton** [comment]
@Wajeed-msft @Abhijit-MSFT @VaraPrasad-MSFT  This issue should not be closed, but the project has been closed.  Please advise as the issue is still very present.

**Comment by VaraPrasad-MSFT** [comment]
@SeanFBrampton : This bug is resolved, could you please check and confirm.

**Comment by SeanFBrampton** [comment]
I checked yesterday before responding. It is not resolved.

I am unable to format an @mention on Android so it appears with the users name when using the "post a message to a teams user and wait" action with power automate.

I tested the code in a post message to teams user connector and everything works. When copying the affected lines of code over to the wait block, nothing comes across properly and there is no functioning mention.

Sean
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by Nikitha-MSFT** [comment]
@SeanFBrampton - Could you please test it on latest version?

**Comment by SeanFBrampton** [comment]
I rebuilt this yesterday using schema 1.2, designed in adaptive-cards.io, and referenced Text formatting in cards - Teams | Microsoft Docs<https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#sample-adaptive-card-with-a-mention> to ensure my formatting was correct.  Within the Post an Adaptive Card to a Teams user and wait for a response, I do not get the correct formatting, see the attached screenshot.

[cid:8008ac98-61fb-4f8e-91d7-ca6007e1485c]

[cid:189626c5-37e2-4ac2-92ca-7e194811fc4f]
[cid:8dc5af73-fe65-41c9-900f-1deb0209967c]

[https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png]<https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#sample-adaptive-card-with-a-mention>
Text formatting in cards - Teams<https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#sample-adaptive-card-with-a-mention>
Describes card text formatting in Microsoft Teams
docs.microsoft.com



Sean Friedman

Analyst, Recreation, Administration and Special Projects

Recreation | City of Brampton

8 Nelson St. West │6th Floor

Brampton, ON │ L6X 4J2

T: 905.874.3594[cid:811cca31-be2f-440d-bceb-0dade4483294] │ C: 416.669.7143[cid:158ab646-a775-4cc9-90a5-3bed670a12e3]

www.brampton.ca<http://www.brampton.ca/>


________________________________

**Comment by Nikitha-MSFT** [comment]
Did you tested the adaptive card on latest team build? Could you please try updating the teams version and check. If you are still facing the issue, please share the IOS Teams vesion.

**Comment by SeanFBrampton** [comment]
[cid:cc488270-cb59-4e3b-a756-329b7d2871cb]

Android version:1416/1.0.0.2021012201


Sean Friedman

Analyst, Recreation, Administration and Special Projects

Recreation | City of Brampton

8 Nelson St. West │6th Floor

Brampton, ON │ L6X 4J2

T: 905.874.3594[cid:f73e7693-563c-48fe-b573-6a3f97bf7d54] │ C: 416.669.7143[cid:79d5d5f5-4c29-41e9-a1d4-e42014b11b2c]

www.brampton.ca<http://www.brampton.ca/>


________________________________

**Comment by Nikitha-MSFT** [comment]
We are looking into it, we don't have ETA to share when it will be fixed.

**Comment by SeanFBrampton** [comment]
Thank you for looking into it.


Sean Friedman

Analyst, Recreation, Administration and Special Projects

Recreation | City of Brampton

8 Nelson St. West │6th Floor

Brampton, ON │ L6X 4J2

T: 905.874.3594[cid:c886a221-7cf1-46ac-840a-5090808d8204] │ C: 416.669.7143[cid:bc264ab3-902e-4ba1-836a-74317a02d9de]

www.brampton.ca<http://www.brampton.ca/>


________________________________

**Comment by ChetanSharma-msft** [comment]
Hello @SeanFBrampton - Sorry for delay in response.
This issue was fixed and rolled out publicly. 

Could you please check and confirm whether you are still facing the same issue or it is already resolved?
