### ISSUE TITLE
Microsoft Teams UI is not getting refreshed when multiple messages are updated

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#2011]
**Issue:**
Updating a card in conversation works only for the latest two posts. Previous messages in a conversation are not updated.  

**Workaround**:
Try switching to another conversation and come back to original thread. 

**Reference:**
https://github.com/microsoft/AdaptiveCards/issues/4599
https://stackoverflow.com/questions/63524023/

**Internal Bug Tracker**: [1147315](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/1147315)

Please continue to follow this issue for updates/progress/questions.

**Comment by Wajeed-msft** [comment]
Updates: This issue has been fixed and code is checked-in. I'll share updates once we have deployment ETA.

**Comment by DivyankaM** [comment]
Hi @Wajeed-msft We are still seeing this issue. Could you please provide an update on the deployment status. Thanks.

cc: @sanjeev9160

**Comment by Wajeed-msft** [comment]
I have pinged for updates on this internally. I'll share update on this thread.

**Comment by johnnycantares** [comment]
Thank you @Wajeed-msft , do you have any further update? because this is causing an issue on our app which is about to go live on the 12th October. Thanks

**Comment by Wajeed-msft** [comment]
Code fix is deployed and it's being verified in internal rings (builds). I am afraid I won't be able to provide exact date, but I'll keep this updated.

**Comment by sulabhjain-Antares** [comment]
Hi @Wajeed-msft - wondering if there is any update on the release of this bug?

**Comment by Nikitha-MSFT** [comment]
Bug is Resolved now, we have tested this at our end, could you please also check and confirm?
The issue is with the Teams client which is fixed now.

**Comment by sulabhjain-Antares** [comment]
Thank you. We can confirm its fixed in the developer preview mode, Is there an ETA on when this will be propagated to production?

**Comment by YJasonY** [comment]
Hi @Wajeed-msft , @Nikitha-MSFT  - any updates on this?

We are still experiencing the issue. Our desktop client version: "You have Microsoft Teams Version 1.3.00.28779 (64-bit). It was last updated on 10/29/20."

We can confirm the fix is present in developer preview mode for both desktop and web clients.

**Comment by Wajeed-msft** [comment]
@Nikitha-MSFT - Could you please check the latest on this?

**Comment by Nikitha-MSFT** [comment]
@wajeed I could repo the issue on the latest issue

**Comment by Nikitha-MSFT** [comment]
Bug is Resolved now, we have tested this at our end, could you please also check and confirm?
The issue is with the Teams client which is fixed now

**Comment by YJasonY** [comment]
Bug confirmed resolved on our end (both Desktop and web clients).

Thanks!
