### ISSUE TITLE
HttpPOST from MessageCard invoke failed

### ISSUE THREAD

**Issue by ikosin** [MicrosoftDocs/msteams-docs#316]
The HttpPOST request failed.
Any request has not been reached target endpoint.

I posted MessageCard using Incoming Webhooks with payload below.
```
  {
    "@type": "MessageCard",
    "@context": "http://schema.org/extensions",
    "text": "Larry Bryant created a new task",
    "potentialAction": [
        {
          "@type": "HttpPOST",
          "name": "Add comment",
          "target": "http://xxxxxxxxx.ngrok.io/comment"
        }
    ]
  }
```

Error messages.
```
[O365ActionPaneController.makeHttpPOSTRequestForConnector()] Http invoke failed: {"data":{"errorCode":"InternalServerError","message":"Failed to execute AEA backend request ConnectorActionRequest. Request Url: https://outlook.office.com/actions/b9a9ddf0-c129-4524-8ea3-bf87fbc8b05d/executeAction/?culture=ja-jp, Request Method: POST, Response Status Code: InternalServerError, Response Headers: X-MSEdge-Ref: Ref A: 28F5CFD870AC4CA88541821C84BC7ED7 Ref B: HK2EDGE0720 Ref C: 2018-11-07T15:32:41Z\r\nDate: Wed, 07 Nov 2018 15:32:41 GMT\r\nX-AspNet-Version: 4.0.30319\r\n"},"status":500,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"url":"https://teams.microsoft.com/api/mt/jp/beta/users/connectors/19:0344722633224ab986a3d4462f817fb5@thread.skype;messageid=1541604731447/1541604731447/executeAction","data":{"inputParameters":[],"actionId":"bf7861fe-9714-4514-bacb-df560bcb82a8","potentialAction":"{\"@type\":\"HttpPOST\",\"@id\":\"bf7861fe-9714-4514-bacb-df560bcb82a8\",\"name\":\"Add comment\",\"target\":\"https://xxxxxxxxx.ngrok.io/comment\",\"headers\":[],\"body\":\"\",\"bodyContentType\":\"\"}","name":"action/connector","integrationId":"lu6xw8mk4k","meta":"{\"connectorSenderGuid\":\"203a1e2c-26cc-47ca-83ae-be98f960b6b2\",\"providerAccountUniqueId\":null,\"connectorConfigurationAlternateId\":\"3de8496598f2482bae4186726f5fc0cf\"}","clientInfo":{"locale":"ja-jp","country":"jp","platform":"Web","clientVersion":"1415/1.0.0.2018101638"}},"headers":{"X-Skypetoken":"pii","Authorization":"pii","Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8","X-RingOverride":"general","x-ms-scenario-id":"666","x-ms-user-type":"user","x-ms-client-type":"web","x-ms-client-env":"msteams-web-prod-asea-02","x-ms-client-version":"1415/1.0.0.2018101638","x-ms-session-id":"405f5e5b-f586-ed45-5753-64faa20c8247"},"counter":"ext_actionable_card_http_post","decrementNetworkRequests":null,"hostName":"teams.microsoft.com"},"statusText":""}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0fd8e4d-f110-36f8-5bd3-db3325b14c01
* Version Independent ID: 717ea854-1d3a-2c15-e495-b6f170fe7aff
* Content: [Using Office 365 Connectors - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors-using#example-connector-message)
* Content Source: [msteams-platform/concepts/connectors/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/connectors/connectors-using.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment]
@ikosin - We are looking into this. Meanwhile, could you please confirm if you have enabled actions on your Connector cards in [Connector Portal](https://outlook.office.com/connectors/publish)?

![image](https://user-images.githubusercontent.com/31851992/48193931-a7279980-e371-11e8-90ee-f2e5639b69bd.png)

**Comment by ikosin** [comment]
@Wajeed-msft - Thank you for your reply.
I did not know that each Connector has a setting to enable action.
However, the one I used for posting is not my own Connector, but the Incoming Webhook Connector which is written in "Setting up a custom incoming webhook".
The Incoming Webhook connector is not set to enable actions?

**Comment by ikosin** [comment]
I thought it might be a problem with the environment of my account. I used "Microsoft Teams for Free" for development, but I upgraded to a paid "Office 365 Business Essentials". Then an HttpPOST request reached to the endpoint.

**Comment by mastef** [comment]
Running into the same issue. Using the demo code, and trying to send any data through `HttpPOST` with the "Incoming webhook connector" on a Microsoft Teams for Free account - and only receiving errors. Not able to submit any http/https post requests so far.

![image](https://user-images.githubusercontent.com/762297/49027731-6df58300-f1d3-11e8-9e28-2713d2825310.png)

And console error : 

![image](https://user-images.githubusercontent.com/762297/49028072-228fa480-f1d4-11e8-9460-609ba064d497.png)

`errorCode`:`InternalServerError`,
`message`:`Failed to execute AEA backend request ConnectorActionRequest`

**Comment by mastef** [comment]
@Wajeed-msft Same thing here. We created now a "Office 365 Developer" account, and then incoming webhooks seem to be able to send HttpPOST requests.

So the question is if customers using the free account would be able to take advantage of MessageCard's with HttpPOST actions that come in through incoming webhooks?

**Comment by billbliss** [comment]
Reopening.

**Comment by Wajeed-msft** [comment]
We are investigating issue with HttpPost for Freemium user.

**Comment by pauldfreeman** [comment]
I'm also having the same issue - using the incoming web hook connector and trying to make an HttpPOST

the error I get is a little different:

`2019-01-11T19:22:58.027Z Err	[O365ActionPaneController.makeHttpPOSTRequestForConnector()] Http invoke failed: {"data":{"errorCode":"Unknown","message":"Object reference not set to an instance of an object."},"status":500,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"url":"https://teams.microsoft.com/api/mt/amer/beta/users/connectors/19:e0XXXXXXXXX444dfbb3cffc7ac07a8717@thread.skype;messageid=15xxxxxx259/154xxxxxxx9/executeAction","data":{"inputParameters":[],"actionId":"e31907e8-xxx-xxx-xxx-85a65...
2019-01-11T19:22:58.027Z War	HTTP request  failed: POST "https://teams.microsoft.com/api/mt/amer/beta/users/connectors/19:e0xxxxxxxxxcffc7ac07a8717@thread.skype;messageid=15472xxxxxxxx59/154xxxxxxx9/executeAction", status: 500, response: {"errorCode":"Unknown","message":"Object reference not set to an instance of an object."}, errorCode: Unknown, requestId: undefined, correlationId: undefined`

**Comment by pauldfreeman** [comment]
Hi

Yes - it was due to our accounts being inadvertantly set to being free accounts. We’ve reapplied our licensing and the issue looks to have gone away. So can confirm this was to do with it being a free account.

**Comment by mastef** [comment]
@Wajeed-msft closing the ticket - does that mean it was fixed now for free accounts?

**Comment by Wajeed-msft** [comment]
We are still tracking this issue. This is still not fixed for Freemium account.

**Comment by finalgamer** [comment]
How is this not fixed yet? Right now we need to use a workaround with opening a webpage to do the action which is just stupid if teams offers the ability to do post request actions.

**Comment by Wajeed-msft** [comment]
@finalgamer - Just to be sure, are you facing this for [Microsof Teams Free](https://products.office.com/en-us/microsoft-teams/free) user account?

**Comment by finalgamer** [comment]
We are not using Microsoft Teams Free. We have subscriptions for **Office 365 Business Premium** and **Office 365 Business Essentials**.

**Comment by finalgamer** [comment]
This is the error I get when performing the post action.

```
2019-03-07T09:35:48.547Z [O365ActionPaneController.makeHttpPOSTRequestForConnector()] Http invoke failed: {"data":{"errorCode":"InternalServerError","message":"Failed to execute AEA backend request ConnectorActionRequest. Request Url: https://outlook.office.com/actions/7c14631a-xxxx-xxxx-xxxx-xxxxxxxxxxxx/executeAction/?culture=en-us, Request Method: POST, Response Status Code: InternalServerError, Response Headers: X-MSEdge-Ref: Ref A: 1BD83EEEB58149B5B87E359F797E7706 Ref B: AM3EDGE0315 Ref C: 2019-03-07T09:35:48Z\r\nDate: Thu, 07 Mar 2019 09:35:48 GMT\r\nX-AspNet-Version: 4.0.30319\r\n"},"status":500,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"url":"https://teams.microsoft.com/api/mt/emea/beta/users/connectors/19:a396e1863c…cc8ec844c@thread.skype;messageid=xxxxxxxxxxxxx/xxxxxxxxxxxxx/executeAction","data":{"inputParameters":[{"id":"feedback","value":"asdf"}],"actionId":"f06e0fd8-xxxx-xxxx-xxxx-xxxxxxxxxxxx","potentialAction":"{\"@type\":\"HttpPOST\",\"@id\":\"f06e0fd8-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"name\":\"Send Feedback\",\"target\":\"https://webhook.site/bbe50020-1390-419b-914c-1864a04f6981\",\"headers\":[],\"body\":\"\",\"bodyContentType\":\"\"}","name":"action/connector","integrationId":"u8xiqgdofv","meta":"{\"connectorSenderGuid\":\"203a1e2c-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"providerAccountUniqueId\":null,\"connectorConfigurationAlternateId\":\"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\"}","clientInfo":{"locale":"en-us","country":"us","platform":"Web","clientVersion":"1415/1.0.0.2019022139"}},"headers":{"X-Skypetoken":"pii","Authorization":"pii","Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8","X-RingOverride":"general","x-ms-scenario-id":"2234","x-ms-user-type":"user","x-ms-client-type":"web","x-ms-client-env":"msteams-web-prod-ukso-02","x-ms-client-version":"1415/1.0.0.2019022139","x-ms-session-id":"cc0e5992-b522-bdd7-b91b-a9177be39a73"},"counter":"ext_actionable_card_http_post","decrementNetworkRequests":null,"hostName":"teams.microsoft.com"},"statusText":""}
```

I x'ed out some information I would not like to post publicly.

Request should have been sent to https://webhook.site/bbe50020-1390-419b-914c-1864a04f6981 which is a simple online request capture tool.

Action is taken from an example in the teams doc.

**Comment by finalgamer** [comment]
This is the error I get when performing the post action.

`
2019-03-07T09:35:48.547Z [O365ActionPaneController.makeHttpPOSTRequestForConnector()] Http invoke failed: {"data":{"errorCode":"InternalServerError","message":"Failed to execute AEA backend request ConnectorActionRequest. Request Url: https://outlook.office.com/actions/7c14631a-xxxx-xxxx-xxxx-xxxxxxxxxxxx/executeAction/?culture=en-us, Request Method: POST, Response Status Code: InternalServerError, Response Headers: X-MSEdge-Ref: Ref A: 1BD83EEEB58149B5B87E359F797E7706 Ref B: AM3EDGE0315 Ref C: 2019-03-07T09:35:48Z\r\nDate: Thu, 07 Mar 2019 09:35:48 GMT\r\nX-AspNet-Version: 4.0.30319\r\n"},"status":500,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"url":"https://teams.microsoft.com/api/mt/emea/beta/users/connectors/19:a396e1863c…cc8ec844c@thread.skype;messageid=xxxxxxxxxxxxx/xxxxxxxxxxxxx/executeAction","data":{"inputParameters":[{"id":"feedback","value":"asdf"}],"actionId":"f06e0fd8-xxxx-xxxx-xxxx-xxxxxxxxxxxx","potentialAction":"{\"@type\":\"HttpPOST\",\"@id\":\"f06e0fd8-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"name\":\"Send Feedback\",\"target\":\"https://webhook.site/bbe50020-1390-419b-914c-1864a04f6981\",\"headers\":[],\"body\":\"\",\"bodyContentType\":\"\"}","name":"action/connector","integrationId":"u8xxxxxxxx","meta":"{\"connectorSenderGuid\":\"203a1e2c-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"providerAccountUniqueId\":null,\"connectorConfigurationAlternateId\":\"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\"}","clientInfo":{"locale":"en-us","country":"us","platform":"Web","clientVersion":"1415/1.0.0.2019022139"}},"headers":{"X-Skypetoken":"pii","Authorization":"pii","Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8","X-RingOverride":"general","x-ms-scenario-id":"2234","x-ms-user-type":"user","x-ms-client-type":"web","x-ms-client-env":"msteams-web-prod-ukso-02","x-ms-client-version":"1415/1.0.0.2019022139","x-ms-session-id":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"},"counter":"ext_actionable_card_http_post","decrementNetworkRequests":null,"hostName":"teams.microsoft.com"},"statusText":""}
`

I x'ed out some information I would not like to post publicly.

Request should have been sent to https://webhook.site/bbe50020-1390-419b-914c-1864a04f6981 which is a simple online request capture tool.

Action is taken from an example in the teams doc.

**Comment by Wajeed-msft** [comment]
Could you please share your Connector id?

**Comment by finalgamer** [comment]
Is it one of these?
 
`integrationId: "u8xiqgdofv"`

`"connectorSenderGuid":"203a1e2c-26cc-47ca-83ae-be98f960b6b2"`

`"connectorConfigurationAlternateId":"a67dd67ef9d44af58a7c05260916cf3f"`

**Comment by Wajeed-msft** [comment]
@finalgamer - Are you trying Incoming Webhook? Or Did you [create your own Connector](https://docs.microsoft.com/en-us/outlook/actionable-messages/connectors-dev-dashboard#build-your-own-connector)?
![image](https://user-images.githubusercontent.com/31851992/53953860-8d694980-40fa-11e9-8e9a-69a5d5f47c30.png)

**Comment by finalgamer** [comment]
We are using Incoming Webhook

**Comment by Wajeed-msft** [comment]
@finalgamer - Could you please share the email id of user who performed the action? If it's not a demo accout which you could share publicly then you could share it via email to us on our [Developer Support alias](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback).

**Comment by finalgamer** [comment]
@Wajeed-msft They were added by my account: michele.dellaneve (at) livesystems.ch

**Comment by Wajeed-msft** [comment]
@finalgamer - Could you please try this again and provide latest failure details?

**Comment by XimenaWang** [comment]
@Wajeed-msft - Hi, I'm also having the same issue - using the connector I registered ( and I added the Target url in the  Actions URL of Connector Portal ) , and trying to make an HttpPOST .  
my json payload below:
![image](https://user-images.githubusercontent.com/30890958/56634834-41298880-6618-11e9-87fc-2f665fa87bfe.png)

the error follows:
![image](https://user-images.githubusercontent.com/30890958/56634798-21926000-6618-11e9-9d92-9787316e6ed8.png)

Can you give me some advice, thanks!

**Comment by Wajeed-msft** [comment]
@XimenaWang - Are you trying this for Freemium user? This is still not supported for Freemium user.
If you are getting this for normal O365 tenant member, could you please share the email id of user who performed the action?

**Comment by mastef** [comment]
@Wajeed-msft If this is not officially supported for freemium users, please add a note or warning in the documentation, instead of having people run into this when following the documentation's test setup.

Because right now the documentation starts with "Any user can connect a team to services...", but only freemium users get these cryptic errors.

**Comment by billbliss** [comment]
@mastef it _should_ work, but it doesn't. We are continuing to work with the team that owns that codepath to fix this.

**Comment by XimenaWang** [comment]
@mastef - Hi, Teams can send post to my API successfully. I just replaced my previous logic with this simple code "hello world", and after clicking the button "acknowledge", I got this message "Hello World". So the post of Teams works, just can't execute my API previous function through Teams, may be a permission issue. You can have a try to send the message only in the API.

my API simple code:
![image](https://user-images.githubusercontent.com/30890958/56861505-4ce9b780-6956-11e9-8ac0-ab51ce05742c.png)

the success Post:
![image](https://user-images.githubusercontent.com/30890958/56861552-ac47c780-6956-11e9-8c34-ba8c1fd28274.png)

my json payload:
![image](https://user-images.githubusercontent.com/30890958/56861606-51fb3680-6957-11e9-888b-119c105b0d15.png)

**Comment by kumarkunal229** [comment]
@Wajeed-msft . I am facing the same issue and unable to perform httppost action from message card. need help !

**Comment by iabukai** [comment]
Same here: 
https://stackoverflow.com/questions/59719288/unable-to-send-http-post-request-from-microsoft-teams-messagecards-potention-ac/59725280#59725280

**Comment by Wajeed-msft** [comment]
@iabukai - Are you facing this issue for non Freemium user? Also, HTTP post action work only in the same tenant where Connector is registered unless it's approved and published in App Store.

**Comment by mcouvill** [comment]
I am a non freemium user and having this issue as well. It doesn't matter what domain I use. Having to Publish it first is counter productive since I don't want to publish until I know it actually works. Can we get some clear communication and documentation as to how this is actually supposed to work because clearly what is there is wrong.

**Comment by timdonovanuk** [comment]
Same +1

**Comment by balu1343** [comment]
Hi ,
I have an internal API that I’m making available through my prod server. Now I want to call that API from a MessageCard HTTPPost action in Teams. When I click on the action button I do not see any errors, and Fiddler shows me a 200 response and I can see the token in the authorization header and the below in the body:{"status":"Completed","actionId":"7e3b1ab6-3320-4f11-92e3-8db3909dcb1f","performedAt":"2020-07-29T04:38:11.5903214Z","properties":{"displayMessage":""}} 
But nothing happens after that on the Teams (im expecting an rely commnet). 

Can you please share the card JSON which we can use.
As per some docs i have tried keeping headers={
“content-type”:”application/json;charset=UTF-8″,
“CARD-UPDATE-IN-BODY”: true,
“CARD-ACTION-STATUS”: "has been Approved”
}

**Comment by taylor-clark** [comment]
Is there any clear documentation on what is and isn't allowed? I'm using a free version of Teams and am running into this issue with incoming webhook. I would like to allow the user to enter text on the card, submit,  then post that text back out to a 3rd party system. I consistently get **Could not complete the requested action. Please try again later.**
Is there a bug, is this not allowed for Free accounts, or are non-marketplace webhooks unable to post back to external services?

**Comment by baluvijay** [comment]
hi, its 2022 and you guys still havent fixed this issue

**Comment by Prasad-MSFT** [comment]
Hi @mcouvill , @baluvijay, @taylor-clark , @totechite - Could you please let us know if you are still facing this issue and looking for any help?

**Comment by baluvijay** [comment]
I left the company for which I was trying to implement this feature, so I
have no idea whats happening now

**Comment by mastef** [comment]
Lmao @Prasad-MSFT why don't you make a free ms account and test it yourself. You guys had 5 years to fix it.

A horror compared to slack integration.

**Comment by Prasad-MSFT** [comment]
Apologies. We understand it. Now we tested the issue and raised an ICM. We will inform in this thread when we get any update from engineering team.

**Comment by MarioBinder** [comment]
ping, ... it is still broke

almost 5 year old issue, 
oh my, if I worked so "hard" I would probably have been unemployed long ago.

**Comment by stevelee2497** [comment]
Still facing this issue. I send the same MessageCard JSON with httpPost action in 2 ways: Incoming Webhook Url and Custom Connector Webhook Url. With Incoming Webhook, I can react to the message successfully, but got 500 InternalServerError when reacting to the message that was sent via Custom Connector. 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/24190646/4a57480e-0952-4f87-a896-5e2859755ddc)

**Comment by pradeepananth** [comment]
Just clarifying here that the original issue is no longer valid since Microsoft Teams Free (classic), where the original issue was occurring,  has been retired  https://www.microsoft.com/en-us/microsoft-teams/free-classic-retirement?rtc=1&ocid=cmmpnxsvbuq&tenantId=b9c8c2a0-2682-4d93-9613-d9baf25d3fb1


Actions with Incoming Webhook has been working fine in Microsoft 365 work or school accounts. @stevelee2497 - Since your issue is unrelated to the original post as your current issue is neither with Incoming Webhook (rather custom connector) nor Teams free, could you please open a separate issue for this custom connector case?

**Comment by pradeepananth** [comment]
Original issue is related to Teams for Free and there are no plans to support Connectors in free or personal accounts.

**Comment by temitopeog** [comment]
@pradeepananth this is still not working for me & I use the Teams (work or school) version. Is there anything special I need to be doing? Happy to share more information

**Comment by pradeepananth** [comment]
@temitopeog - Please submit as a separate issue for Teams work.

**Comment by temitopeog** [comment]
New issue created on https://github.com/MicrosoftDocs/msteams-docs/issues/10557

Thank you @pradeepananth
