### ISSUE TITLE
iOS not handling task/fetch adaptive card submit action properly

### ISSUE THREAD

**Issue by BrendanAndrade** [MicrosoftDocs/msteams-docs#3499]
I have an adaptive card that is sent to a teams channel with an action like: 

"type": "ActionSet",
"actions": [
    {
        "type": "Action.Submit",
        "id": "edit",
        "title": "Edit",
        "data": {
            "foo": "bar",
            "msteams": {
                "type": "task/fetch"
            }
        }
    }
]

When that button is clicked in browser, desktop app, or android, the activity comes to the bot as: 

{
   "name":"task/fetch",
   "type":"invoke",
   ....

When the same button is clicked on iOS, it opens a modal with a duplication of the card. I click the "Edit" button again and the activity comes to the bot as 

{
   "name":"task/submit",
   "type":"invoke",
   ...

I believe this to be a bug in the iOS version of teams. 

I tried returning
{task: { 
    type: 'continue', 
    value: {
                    width:"large",
                    height:"large",
                    title:"Edit",
                    card: {
                        contentType: "application/vnd.microsoft.card.adaptive",
                        content: ...card content...
                    }
    }
}}

using handleTeamsTaskModuleSubmit but that isn't working with the iOS app. 

Is this a bug? Is there a workaround for iOS?

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800b748d-fb81-8f4d-adc2-3ee610394346
* Version Independent ID: b1ebd031-c5cd-ffeb-d9b2-d752511900db
* Content: [Using Task Modules in Microsoft Teams bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-bots)
* Content Source: [msteams-platform/task-modules-and-cards/task-modules/task-modules-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/task-modules/task-modules-bots.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by BrendanAndrade** [comment]
A quick update: I was able to send a card via handleTeamsTaskModuleSubmit in response to the activity from the iOS app but no card I send is rendering. It should the card's title and a blank white box. I tried some pretty simple cards and none worked.

**Comment by Mamatha-MSFT** [comment]
@BrendanAndrade - I will repro at my end and will get back to you.

**Comment by Mamatha-MSFT** [comment]
@BrendanAndrade - I am able to repro the issue. In IOS teams channel, the task module is not fetching where as it's working in teams personal app. We will raise a bug for this issue and will inform you.

**Comment by Mamatha-MSFT** [comment]
@BrendanAndrade - We have created a bug on this issue and concerned engineering team is working on it.

**Comment by Jagadeesh-MSFT** [comment]
Hi @BrendanAndrade - thanks for providing the above code. We have figured out the parity issue. This will be fixed soon. In the meantime to unblock yourself, you can either remove `turnContext.SendActivityAsync(reply)` from your `OnTeamsTaskModuleFetchAsync` function or use the synchronous version of `OnTeamsTaskModuleFetchAsync` function.

**Comment by BrendanAndrade** [comment]
@Jagadeesh-MSFT I'm not using those functions. I'm using the node sdk and extending the TeamsActivityHandler class. 

The relevant code is just:
export default class MessageExtension extends TeamsActivityHandler {
    async handleTeamsTaskModuleFetch(context, action) {
        const card = **some card**:
        const task = { 
                task: {
                    type: 'continue',
                    value: {
                        width:"large",
                        height:"large",
                        title:"Title",
                        card: {
                            contentType: "application/vnd.microsoft.card.adaptive",
                            content: card
                        }
                    }
                }
            };

        return task;
    }
}

**Comment by usman-javed-dev** [comment]
Is there any update on this?

**Comment by v-chetsh** [comment]
@usman-javed-dev - Raised bug has already been fixed by engineering team.
Could you please check it once from your end and let us know.

**Comment by usman-javed-dev** [comment]
Then why it's OPEN?
and it is still not working on iOS, double checked.

**Comment by Nivedipa-MSFT** [comment]
@usman-javed-dev - We have tested this issue on IOS 15.3 and Teams version 3.22.0. Its working fine at our end. 
When button is clicked on iOS the trigger goes to the OnTeamsTaskModuleFetchAsync() function.
Could you please try to update the Teams version and check again.

**Comment by usman-javed-dev** [comment]
I am using following `fetch` code:

```
async handleTeamsTaskModuleFetch(_: TurnContext, { data: { commandId } }: TaskModuleRequest): Promise<TaskModuleResponse> {
  return {
    task: {
      type: 'continue',
      value: {
        width: 'large',
        height: 'large',
        title: 'Test',
        url: `my-url.com/test`
      }
    }
  };
}
```

And `submit` code is:

```
async handleTeamsMessagingExtensionSubmitAction(ctx: TurnContext, { commandId, data }: MessagingExtensionAction) {
  console.log('here now...');
}
```

That console log doesn't work in iOS but it works in Android.

This task/fetch is called from this piece of code:

```
CardFactory.adaptiveCard({
  type: 'AdaptiveCard',
  $schema: 'http://adaptivecards.io/schemas/adaptive-card.json',
  version: '1.3',
  body: [
    {
      type: 'ActionSet',
      actions: [
        {
          type: 'Action.Submit',
          title: 'Test Title',
          data: {
            msteams: {
              type: 'task/fetch'
            },
            commandId: 'test'
          }
        }
      ]
    }
  ]
});
```

Please notice it's `adaptive-card : v1.3`, please reproduce the issue and let me know, if you can't, so that we can have a meeting on it.

**Comment by Nivedipa-MSFT** [comment]
@usman-javed-dev - Could you please check using latest version of adaptive-card(v1.11)?

**Comment by usman-javed-dev** [comment]
No I can't because android teams has issue even if I use 1.7, right now I am using 1.3, when your team reviewed our teams app, they rejected it, because if was not working at all, so downgraded and it worked. Don't know why 1.3 is not working, it should work as expected. If it's not working on 1.3 on iOS, then android/web/desktop shouldn't work either.

**Comment by Nivedipa-MSFT** [comment]
We have tested with adaptive card v1.3. Its working fine at our end. Could you please share your sample code zip to check at our end?

**Comment by usman-javed-dev** [comment]
Check my code snippet somewhere above.

Add that and check, I am not getting console logs in iOS.

**Comment by Nivedipa-MSFT** [comment]
@usman-javed-dev - We have tried below adaptive card v1.3

 ```
 {
  "type": "AdaptiveCard",
  "version": "1.3",
  "body": [
    {
      "type": "TextBlock",
      "text": "Test",
      "wrap": true
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "id": "fetchtask",
      "title": "FetchTask",
      "data": {
        "msteams": {
          "type": "task/fetch"
        }
      }
    }
  ]
}
```
When button is clicked on iOS the trigger goes to the OnTeamsTaskModuleFetchAsync() function.
```
      protected override Task<TaskModuleResponse> OnTeamsTaskModuleFetchAsync(ITurnContext<IInvokeActivity> turnContext, TaskModuleRequest taskModuleRequest, CancellationToken cancellationToken)
        {
        
        }
```
