### ISSUE TITLE
Configurable properties not working

### ISSUE THREAD

**Issue by NicolasMCAG** [MicrosoftDocs/msteams-docs#3565]
Hi,

I'm testing the configurable properties for Teams apps on my dev tenant, and it seems the feature is not working.

I tried uploading to the Teams admin center a simple app manifest using schema 1.10 without configurable properties, and it gets uploaded without problems. If I take the same manifest, add the configurable properties section, and increase the app version number, the upload fails, either if I try to update the existing app or if I remove it and upload it as a new app.

Here are the manifests I tried uploading:

[Manifests.zip](https://github.com/MicrosoftDocs/msteams-docs/files/6596353/Manifests.zip)

Can anyone provide some insight on what is wrong, please?

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
We are checking the manifest and trying to repro at our end we will get back to you.

**Comment by heath-hamilton** [comment]
@NicolasMCAG, this may be a manifest issue. We recently discovered an error in the [docs that has been fixed](https://docs.microsoft.com/microsoftteams/platform/resources/schema/manifest-schema#configurableproperties): Instead of `websiteUrl`, which you have in your manifest, you need the `developerUrl` property. Please let us know if this solves the issue.
![image](https://user-images.githubusercontent.com/66389316/121094755-fa6d5d00-c7a3-11eb-858d-90fd65048df3.png)

**Comment by NicolasMCAG** [comment]
Hi @heath-hamilton,

I tried changing the property you mention, and still no luck. I also tried removing all the properties except **name**, and still doesn't work.

Here are the manifests I tried...
[Manifests with configurable properties.zip](https://github.com/MicrosoftDocs/msteams-docs/files/6614129/Manifests.with.configurable.properties.zip)

For the record, before uploading the customizable manifests I removed the app from the Teams admin center, and increased the version number on the manifests.

If it helps, I got a 502 from the POST request to **https://graph.microsoft.com/beta/appCatalogs/teamsApps**  with request id **ea8c9ff6-9868-4d1e-b84a-ff8d3644d875** and date **2021-06-08T06:51:12**

**Comment by heath-hamilton** [comment]
Hi @NicolasMCAG, how are you publishing your app? You can only test this feature with apps published to the Teams store (or AppSource). You can't test this feature by sideloading or publishing to a tenant's app catalog.

**Comment by NicolasMCAG** [comment]
Hi @heath-hamilton,

Thank you for your answer, indeed I'm sideloading the app, so that solves the mystery.

Can you give me some insight if this feature being available for sideloaded apps in the near future?

**Comment by heath-hamilton** [comment]
Hi @NicolasMCAG, glad to help! I'm not aware of plans to support this feature with sideloaded apps. The idea is the app publisher can choose to simply allow their users to customize some basic aspects of the app. Users who then get the app from the store can configure these changes (for example, swapping out the icon) in the Teams admin center and test the changes in their own tenant.

Does this help? Please let me know if you see another use case for this feature.

**Comment by NicolasMCAG** [comment]
Hi @heath-hamilton,

In our case we are migrating some features from our product to Teams, and we are doing this using Teams apps.

Right now we are considering publishing our apps, but that is still far away for us, for the moment we rely on sideloading the apps, and of course, all of our customers want customized manifests. The way we split the features helps us have quite static manifests, except for the customer customizations.

That's why having this feature supported for sideloaded apps is important for us.

Once again, thank you for your help.
