### ISSUE TITLE
Deeplinking to Apps does not work with mobile

### ISSUE THREAD

**Issue by figgsoftware** [MicrosoftDocs/msteams-docs#4393]
This functionality is great, but it does not work for Teams mobile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@figgsoftware - Could you Please share what you are trying to deeplinking and which mobile you are using ios or android?

**Comment by v-chetsh** [comment]
Ok thanks.
We will check and redirect it accordingly.

**Comment by Prasad-MSFT** [comment]
@figgsoftware - The issue is fixed now. Please verify.

**Comment by Prasad-MSFT** [comment]
We are closing the issue for now. Please feel free to re-open if needed.

**Comment by figgsoftware** [comment]
@Prasad-MSFT Thx for the update. Still not working for me. Is it a special version of the Android and iOS Teams app that does support it? I don't have any pending updates in Google Play for the Teams app.

**Comment by v-chetsh** [comment]
@figgsoftware - We will reverify it from our end and let you know.

**Comment by figgsoftware** [comment]
Thx @v-chetsh ! Here is the deep link to our app that we are testing with: https://teams.microsoft.com/l/app/d3d1be68-066c-4967-a74b-9edcf902dcfb

**Comment by Nivedipa-MSFT** [comment]
@figgsoftware - We have tested on Android 11 . Its working fine at our end. For IOS we are checking with the engineering team. We will let you know once we have any update.

**Comment by Nivedipa-MSFT** [comment]
@figgsoftware - We have informed Engineering team about the IOS issue and they are currently working on the fix. We will inform you once we have further update.

**Comment by Nivedipa-MSFT** [comment]
@figgsoftware - We have tested below deeplink on IOS 16.2 and Teams version 4.22.1 and its working.
 https://teams.microsoft.com/l/app/d3d1be68-066c-4967-a74b-9edcf902dcfb
 
 Could you please test this and confirm?
