### ISSUE TITLE
Carousel rendered in full msteams width

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4394]
Copied from: https://github.com/microsoft/botbuilder-dotnet/issues/5903
Posted by: @JordyGit

**Details:**

Adaptive Card property, see [Documentation here](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#full-width-adaptive-card):
"msTeams": { "width": "full" },

Carousel made with:
MessageFactory.Carousel

Is your feature request related to a problem? Please describe.
Adaptive cards can use the msteams full witdth property to be rendered bigger in teams, alto using the same cards in a carousel or adding the property manually to a carousel, the carousel keeps being rendered smaller.

Describe the solution you'd like
Carousels rendered wider if the property is present or when the adaptive cards in the carousel have the property.

Describe alternatives you've considered
/

Additional context
/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 001a12ea-30fa-d626-18a9-02a518bfb37f
* Version Independent ID: e5f5f69e-66e9-d1b2-e19a-485d0ffcd6fa
* Content: [Text formatting in cards - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-format.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
@jordygit - We got an update from the engineering team that they are deploying a hotfix to make the carousel width aligning with the older version. however, "full width" flag in carousel adaptive cards will be taken care later. Hence we do not have any ETA to share. I will keep you posted if there is any update.

**Comment by Meghana-MSFT** [comment]
The hot fix has been deployed. We tested and its rendering fine. 
![image](https://user-images.githubusercontent.com/81138249/159915734-5e0250fe-4586-423f-863c-b7f78985d86a.png)

**Comment by Meghana-MSFT** [comment]
This issue has been fixed and we have verified the fix. Attaching a screenshot of carousel cards with and without full width. Could you please check once and confirm the fix?

![image](https://user-images.githubusercontent.com/81138249/161036134-c0ea1e8e-cf18-4e3f-9d61-72368dad297b.png)

**Comment by juanmanuelpuhl** [comment]
@Meghana-MSFT For Teams desktop and Teams browser is working fine, but. if I open the app in a popup then the carousel is showed smaller (I tried with and without the Full option for width). Is this case a known issue?

**Comment by Meghana-MSFT** [comment]
@juanmanuelpuhl  We will check this at our end and get back to you.

**Comment by Meghana-MSFT** [comment]
We see the size is same in a popup as well, attaching screenshots of the same, could you please confirm if you are referring to the same issue ?

Normal view : 
![image](https://user-images.githubusercontent.com/81138249/166719999-9e40cbed-7eca-4ce7-962d-926072a7eed2.png)
Popout chat view  : 
![image](https://user-images.githubusercontent.com/81138249/166720114-a0a26d84-0bc1-40ab-ace9-4492b8436436.png)

**Comment by JordyGit** [comment]
I have checked and can confirm the carousels are still not full width and in some cases and even worse than before (**unusable!**).

I'll post some more examples very soon.

![image](https://user-images.githubusercontent.com/33500507/172404688-ff484c30-d24c-452a-ac0c-e9a5ae7734e7.png)

**Comment by JordyGit** [comment]
I have investigated it further.

Full width works perfect in private and group conversations for as well normal cards as carousels! Thanks for that!

It seems to still have **issues in Teams/Channels for carousels** while normal cards do work fine there with full width.
**In some cases the carousel also doesn't slide as it should** and has weird behavior. See the GIFS I'll add below.

![image](https://user-images.githubusercontent.com/33500507/172556980-577781c1-511b-48ca-b4c4-9bc9570b89d3.png)

![carousel offsets 2](https://user-images.githubusercontent.com/33500507/172556916-5c8cdf58-7c24-48a1-9bc3-d2de90cf24d1.gif)

![carousel offsets](https://user-images.githubusercontent.com/33500507/172556923-695cc804-965b-4fb7-b820-b10d553de2d1.gif)

**Comment by Meghana-MSFT** [comment]
We will check these scenarios and reopen the bug as well.

**Comment by Wajeed-msft** [comment]
@JordyGit - removed tag due to which this issue was marked as inactive.

**Comment by Meghana-MSFT** [comment]
@JordyGit - We are able to repro this issue on Desktop and web apps. We have informed the engineering team and team will look into this. We will keep you posted on the updates.

**Comment by Nivedipa-MSFT** [comment]
@JordyGit - The bug has been resolved. Could you test it and let me know if everything is working as expected?

**Comment by JordyGit** [comment]
@Nivedipa-MSFT It looks to be better thanks! It's still not as wide as a single card but at least it renders not as small as before and the paging works nicely. See screenshot below showing a carousel with full width attachments first, and a normal card with full width below, in the MS Teams desktop app 25332.1210.4188.1171.

Carousel created using `MessageFactory.Carousel(activity.Attachments);` while each attachment has `"msteams": {  "width": "Full" }` set.

<img width="937" height="651" alt="Image" src="https://github.com/user-attachments/assets/b11f8983-f8ac-441b-947e-7ddbd17823ce" />

**Comment by JordyGit** [comment]
> [@JordyGit](https://github.com/JordyGit) - removed tag due to which this issue was marked as inactive.

@Wajeed-msft can you remove the tag again? Thanks

**Comment by JordyGit** [comment]
@Meghana-MSFT can you remove the needs-author-feedback tag please...
