### ISSUE TITLE
[Android] Date function in adaptive card is missing month name

### ISSUE THREAD

**Issue by matthiasdilger** [MicrosoftDocs/msteams-docs#4500]
Bot sends card to user:

```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "Your package will arrive on {{DATE(2017-02-14T06:00:00Z, SHORT)}} at {{TIME(2017-02-14T06:00:00Z)}}",
            "wrap": true
        }
    ]
}
```

Teams android app is showing "M2" instead of "Feb", "M11" instead of "Nov" etc.

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - We have repro this issue.We have raised the bug for it and Concerned team is looking into it.We will let you know if there is any update.

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger -For this bug the fix will be added to the up coming release.

**Comment by matthiasdilger** [comment]
@Nivedipa-MSFT Hi, any updates on this? I am using version 1416/1.0.0.2021194504/1209 and the issue is still present

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - Engineering team is looking into it. We will inform you once we have any update.

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - The bug is fixed now. Could you please check it once.

**Comment by matthiasdilger** [comment]
@Nivedipa-MSFT Thanks, I just tried with version 1416/1.0.0.2021195305/1216 and the issue is still present. I will wait for an app update from the store and get back to you.

**Comment by matthiasdilger** [comment]
This issue has been fixed, thanks
