### ISSUE TITLE
Dedicated graphics card always in use

### ISSUE THREAD

**Issue by kronarthereal** [MicrosoftDocs/msteams-docs#826]
Since the next to last release Mac version of Microsoft Teams Helper always activates the dedicated graphics card. This was not the case for older versions. Causes more heat and power consumption on battery....
Please fix dependency or introduce a setting...

Thank you
Best regards.
Roland

**Comment by Gousia-MSFT** [comment]
@kronarthereal We have a bug for this. We are looking into it. Thanks!

**Comment by Gousia-MSFT** [comment]
@kronarthereal This is fixed now. Please check.

**Comment by HendricksonTyler** [comment]
@Gousia-MSFT This is definitely still an issue. Can you please provide a fix?

**Comment by Marcus1571** [comment]
Nov 19, 2019: this is definitely still an issue! Not solved at all.
