### ISSUE TITLE
Teams Webhooks with emoji no longer work

### ISSUE THREAD

**Issue by devIlluSioN** [MicrosoftDocs/msteams-docs#8539]
Hello, 

Adaptive cards that contain emoji no longer work with Teams Webhook : 

Work : 
`{
    "type": "message",
    "attachments":
    [
        {
            "contentType": "application/vnd.microsoft.card.adaptive",
            "content":
            {
                "type": "AdaptiveCard",
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "version": "1.4",
                "action": "type",
                "body":
                [
                    {
                        "type": "Container",
                        "items":
                        [
                            {
                                "type": "ActionSet",
                                "actions":
                                [
                                    {
                                        "type": "Action.OpenUrl",
                                        "title": "Go To Microsoft",
                                        "url": "https://www.microsoft.com"
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        }
    ]
}`

Doesn't work : 
`{
    "type": "message",
    "attachments":
    [
        {
            "contentType": "application/vnd.microsoft.card.adaptive",
            "content":
            {
                "type": "AdaptiveCard",
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "version": "1.4",
                "action": "type",
                "body":
                [
                    {
                        "type": "Container",
                        "items":
                        [
                            {
                                "type": "ActionSet",
                                "actions":
                                [
                                    {
                                        "type": "Action.OpenUrl",
                                        "title": "😐 Go To Microsoft",
                                        "url": "https://www.microsoft.com"
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        }
    ]
}`

**Comment by WinterBear** [comment]
Getting the same issue, this doesn't seem to impact all emojis, ⚠️ works fine for me, but 😃😐😊 do not.

**Comment by rudemex** [comment]
I have the same problem.

```
{
   "@type":"MessageCard",
   "@context":"http://schema.org/extensions",
   "themeColor":"e7dc58",
   "summary":"Release",
   "sections":[
      {
         "activityTitle":"🎉 New release in Monorepo Test is out!",
         "activitySubtitle":"2023-04-24T20:30:28.000+00:00",
         "facts":[
            {
               "name":"📦 Package:",
               "value":"@scope/pkgtest"
            },
            {
               "name":"🏷️ Version:",
               "value":"v0.1.13"
            }
         ],
         "markdown":true
      },
      {
         "text":"<h2>Description</h2>",
         "markdown":true
      },
      {
         "text":"👨‍💻 Chores\n\n* remove commit ([538aed4](http://google.com.ar))\n\n",
         "markdown":true
      }
   ],
   "potentialAction":[
      {
         "@type":"OpenUri",
         "name":"📚 Documentation",
         "targets":[
            {
               "os":"default",
               "uri":"https://google.com.ar"
            }
         ]
      },
      {
         "@type":"OpenUri",
         "name":"🐛 Report an Issue",
         "targets":[
            {
               "os":"default",
               "uri":"https://google.com.ar"
            }
         ]
      }
   ]
}
`
``

**Comment by danygold** [comment]
I have the same problem.
This is a critical issue. Please fix it asap

**Comment by pirem** [comment]
We also have the same problem.

**Comment by nbevans** [comment]
Same problem. Worked fine for years with our MessageCard webhooks into Teams. But stopped working yesterday. HTTP status 200, but a response body text saying status 400. So causing a silent failure... don't return HTTP 200 when it's a failure people...

**Comment by johnatas-x** [comment]
Hey,
Same problem for me, MessageCard with 🚀 emoji returns 400 since yesterday morning.
Note that MessageCard with❌ & ✔️ emojis returns 200.

**Comment by ChetanSharma-msft** [comment]
Hello Everyone,
Thanks for reporting your issues.
We will look into it and let you know the updates soon.

**Comment by Prasad-MSFT** [comment]
Hello Everyone, we tried to repro this issue using the JSON provided above and are able to repro this issue.
JSON Used:
`{ "type": "message", "attachments": [ { "contentType": "application/vnd.microsoft.card.adaptive", "content": { "type": "AdaptiveCard", "$schema": "http://adaptivecards.io/schemas/adaptive-card.json", "version": "1.4", "action": "type", "body": [ { "type": "Container", "items": [ { "type": "ActionSet", "actions": [ { "type": "Action.OpenUrl", "title": "😐 Go To Microsoft", "url": "https://www.microsoft.com" } ] } ] } ] } } ] }`

It throws below error response:
`Webhook message delivery failed with error: Microsoft Teams endpoint returned HTTP error 400 with ContextId MS-CV=BpnM40HzPUqdFC5CL5d1Gg.0..`

JSON Used:
```
{
   "@type":"MessageCard",
   "@context":"http://schema.org/extensions",
   "themeColor":"e7dc58",
   "summary":"Release",
   "sections":[
      {
         "activityTitle":"🎉 New release in Monorepo Test is out!",
         "activitySubtitle":"2023-04-24T20:30:28.000+00:00",
         "facts":[
            {
               "name":"📦 Package:",
               "value":"@scope/pkgtest"
            },
            {
               "name":"🏷️ Version:",
               "value":"v0.1.13"
            }
         ],
         "markdown":true
      },
      {
         "text":"<h2>Description</h2>",
         "markdown":true
      },
      {
         "text":"👨‍💻 Chores\n\n* remove commit ([538aed4](http://google.com.ar))\n\n",
         "markdown":true
      }
   ],
   "potentialAction":[
      {
         "@type":"OpenUri",
         "name":"📚 Documentation",
         "targets":[
            {
               "os":"default",
               "uri":"https://google.com.ar"
            }
         ]
      },
      {
         "@type":"OpenUri",
         "name":"🐛 Report an Issue",
         "targets":[
            {
               "os":"default",
               "uri":"https://google.com.ar"
            }
         ]
      }
   ]
}
```
Error response:
`Webhook message delivery failed with error: Microsoft Teams endpoint returned HTTP error 400 with ContextId tcid=0,server=msgapi-production-wus-azsc1-4-37,cv=nqQlzHtpDkSaPAFt8NYz5A.0,MS-CV=nqQlzHtpDkSaPAFt8NYz5A.0..`

**Comment by mmiddleton3301** [comment]
This is quite a problem - it wouldn't be so bad if the HTTP request came back with an actual 400 (as described in the error message), rather than a 200, as this has been causing the process to silently fail.

In my case, the problem emoji appears to be: 🩺. Adaptive card markup containing ✅ and ❌ seems to work fine, however.

**Comment by nbevans** [comment]
@mmiddleton3301 

The HTTP status 200 is a bigger problem than the problem itself. Agreed.

**Comment by nbevans** [comment]
```json
{
  "potentialAction": [],
  "text": "💬",
  "themeColor": "",
  "title": "",
  "@context": "https://schema.org/extensions",
  "@type": "MessageCard"
}
```

Here's my repo

**Comment by TrianguloY** [comment]
I also confirm the issue.

But I wanted to add that the 'returns 200 if it fails' already happened before, on our case with very big messages. 
From our tests the request returns an error body of '1' if it succeeds, any other string otherwise. Our code (python) is as follows:
```python
result = post(self._hookurl, data=data)
print(result, result.text)
if result.text != '1': raise Exception(result.text)
```

The 'emojis can't be sent' issue is new, but the 'always returns 200 even if it fails' isn't. In any case it should be fixed too.

**Comment by Meghana-MSFT** [comment]
We have raised an ICM with the connectors team. We will keep you posted on the progress. Thank you for your understanding!

**Comment by matixoooo** [comment]
i also confirm that issue, we tryin to send events from robusta and request is like this :

"text": "\ud83d\udd34 HIGH - Failed to pull at least one image in pod test in namespace

when send that request we got error : HTTP 400 ContextId MS-CV=E8NZ5yo9zUKhXDkKjJIt0w.0.

without \ud83d\udd34 everything working .

Oddly enough, two days ago everything was working fine ;)

looking forward for resolve issue guys ;)

**Comment by WilbertWalrus** [comment]
Once again, no proper testing done by Microsoft Team before rolling out changes that affect webhooks, just like Adaptive Card issue that's been going on for more than 4 months now: https://github.com/MicrosoftDocs/msteams-docs/issues/7638 — returning a 200 on a 400 error is simply embarrassing 👿

**Comment by gabrielmocanu** [comment]
We also have the same problem.

**Comment by teodutu** [comment]
Maybe it's a feature aimed at stopping people from mixing emojis with text :man_shrugging:.

**Comment by rudemex** [comment]
These things don't happen with discord. ¬_¬

**Comment by nbevans** [comment]
Yep it's fixed.

**Comment by devIlluSioN** [comment]
Actually it seems to be back to normal for me.
I'm waiting for an official return from the Microsoft team, before declaring victory too quickly 😅

**Comment by Wajeed-msft** [comment]
**Update:** This is fixed. There was a hotfix that got merged around 3AM PST.

**Comment by devIlluSioN** [comment]
Ok it works for me. I closed the issue

Does the hotfix also fix returning a 200 code instead of a 400 code?

**Comment by TrianguloY** [comment]
> Does the hotfix also fix returning a 200 code instead of a 400 code?

I've just tested with a very-long-message and can confirm that the endpoint still returns 200 but with a text content of 413, so no (in this case at least).

`<Response [200]> Webhook message delivery failed with error: Microsoft Teams endpoint returned HTTP error 413 with ContextId MS-CV=/PwEvwmMH0ei5LDKmXJgHw.0..`

**Comment by devIlluSioN** [comment]
Maybe we need to open a new issue

**Comment by Meghana-MSFT** [comment]
> > Does the hotfix also fix returning a 200 code instead of a 400 code?
> 
> I've just tested with a very-long-message and can confirm that the endpoint still returns 200 but with a text content of 413, so no (in this case at least).
> 
> `<Response [200]> Webhook message delivery failed with error: Microsoft Teams endpoint returned HTTP error 413 with ContextId MS-CV=/PwEvwmMH0ei5LDKmXJgHw.0..`

We tested this at our end it gave 200 OK and 1. 
![image](https://user-images.githubusercontent.com/81138249/235287683-a4e9009a-1ee9-4f2f-973b-9a347ce4dfe9.png)

Could you please share the card that you used?

**Comment by TrianguloY** [comment]
> We tested this at our end it gave 200 OK and 1. 
> ![image](https://user-images.githubusercontent.com/81138249/235287683-a4e9009a-1ee9-4f2f-973b-9a347ce4dfe9.png)
> 
> Could you please share the card that you used?

That means the message was not long enough and it succeeded. I think I tested with a textblock of `"test"*1000` ("test" joined 1000 times).
I'm out of my computer for a few days, sorry. On Tuesday I'll provide a working sample to replicate the bug.

**Comment by WilbertWalrus** [comment]
⚠

@Meghana-MSFT @Wajeed-msft — how can we get M365 sales credit back for the time wasted patching our code to have a webhook version without emojis and the hours spent dealing with customers asking where their notifications went?

At the very least, the MSFT developer(s) and PM responsive for this mess (and the embarrassing 400 error showing a 200 success status) should have their pay deducted for that day — and that amount should be given back as credit to paying customers.

@devIlluSioN — understand this issue is closed, but _**every**_ issue ticket where Microsoft is at fault, it should still remain open until they can let us know what actions they have taken to prevent the same bug from happening again and how customers can get credits back for the headache caused; we need to hold these large corporations accountable while they do “fancy” stuff like AI/co-pilot when the quality goes to the crapper on fundamental features and functions for existing products.

**Comment by TrianguloY** [comment]
> Could you please share the card that you used?

I managed to create a working sample with another computer:

```bash
curl -i -H 'Content-Type: application/json' -d @- $WEBHOOK_URL <<EOF
{
   "type":"message",
   "attachments":[
      {
         "contentType":"application/vnd.microsoft.card.adaptive",
         "contentUrl":null,
         "content":{
            "$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
            "type":"AdaptiveCard",
            "version":"1.2",
            "body":[
                {
                "type": "TextBlock",
                "text": "$(head -c 100000 < /dev/zero | tr '\0' '#')"
                }
            ]
         }
      }
   ]
}
EOF
```

This message is the sample from [Send Adaptive Cards using an Incoming Webhook](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL#send-adaptive-cards-using-an-incoming-webhook), but with a text content of 100000 characters.

It returns a status code of 200 OK but with a body of `Webhook message delivery failed with error: Microsoft Teams endpoint returned HTTP error 413`:
![image](https://user-images.githubusercontent.com/10616202/235348801-a3fbf1d6-95d5-4ad9-83a6-a605331b80a0.png)

**Comment by Meghana-MSFT** [comment]
> Webhook message delivery failed with error: Microsoft Teams endpoint returned HTTP error 413

@TrianguloY - 413 error comes when the card exceeds the size limit. We have informed engineering team about the status code 200 OK.  

https://learn.microsoft.com/en-us/microsoftteams/limits-specifications-teams#teams-and-channels

**Comment by devIlluSioN** [comment]
Any update for Http Status 200 with a error inside the payload ? 
(https://github.com/MicrosoftDocs/msteams-docs/issues/8539#issuecomment-1529934866)

**Comment by vdurante** [comment]
I am getting some Azure Cosmos DB exception inside the response payload and the webhook doesn't post the message. Anybody else with this issue?

**Comment by ChetanSharma-msft** [comment]
> 

I apologize for delay in response.
We are actively checking the status of bug fix with engineering team and will update this thread.

Thanks!!

**Comment by Meghana-MSFT** [comment]
> I am getting some Azure Cosmos DB exception inside the response payload and the webhook doesn't post the message. Anybody else with this issue?

This issue has been fixed, could you please verify the fix. Thank you.

**Comment by dcdraper** [comment]
same problem here; hoping for a fix sometime soon :/

**Comment by Meghana-MSFT** [comment]
@dcdraper - Could you please let us know if you are facing the issue with sending emoji or Azure Cosmos DB exception or 400 error showing a 200 success status?

**Comment by dcdraper** [comment]
@Meghana-MSFT sorry I am having the main issue of this thread -- the emojis no longer work, and I get a 200.

**Comment by Meghana-MSFT** [comment]
@dcdraper - Could you please share the JSON with which you are facing this issue as emojis issue has been fixed already.

**Comment by dcdraper** [comment]
@Meghana-MSFT - Sorry, it IS working now. I missed a piece of workaround code that was making it look still broken.  

Everything is good for me, thanks!

**Comment by theknut** [comment]
I'm still getting status code 200 and 413 in the body. This is embarrassing!

**Comment by ChetanSharma-msft** [comment]
Hello @theknut - We have raised the issue and informed engineering team.
We will let you know once we get any further updates from engineering team.

**Comment by Meghana-MSFT** [comment]
@theknut - Please refer this https://github.com/MicrosoftDocs/msteams-docs/issues/9064#issuecomment-1778841578.

**Comment by devIlluSioN** [comment]
The original issue is resolved and the second issue (http error inside payload with status code 200) has its own issue, so I'm closing that issue.
