### ISSUE TITLE
Forced vertical cut-off of a post ("see more / less") 

### ISSUE THREAD

**Issue by grietine** [MicrosoftDocs/msteams-docs#8808]
After upgrade to the latest version, I've noticed a change on how AdaptiveCards are displayed. 

Currently, we have implemented a custom AdaptiveCard with all the necessary info, but in order to fully view it you have to click "see more" button. It's a small, but impactful change to our workflow. As everything in that post is important and especially that all the action buttons are on the bottom of the AdaptiveCard.

Can you implement a setting for channel or user to set a view size behavior of "see more / less"? Instead of forcefully deciding what's cluttering and best for the user, let the user to decide what he wants in this case.

**Screenshots:**

**See more:**
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/9082268/2f4ec424-232b-495a-948e-1b362b7c1f2b)

**See less:**
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/9082268/6b205e1d-b287-4cfd-8dcd-83dd742f4e66)

Thank you for your time!

**Microsoft Teams Version:** 1.6.00.12455 (64-bit)

**Comment by grietine** [comment]
Sure! 

<details>
  <summary>AdaptiveCard JSON:</summary>

```json
{
	"Type": "message",
	"Summary": "[REDACTED]",
	"Attachments": [
		{
			"ContentType": "application/vnd.microsoft.card.adaptive",
			"Content": {
				"type": "AdaptiveCard",
				"version": "1.3",
				"body": [
					{
						"type": "Container",
						"items": [
							{
								"type": "TextBlock",
								"size": "extraLarge",
								"weight": "bolder",
								"color": "attention",
								"text": "[REDACTED]"
							}
						]
					},
					{
						"type": "Container",
						"items": [
							{
								"type": "ColumnSet",
								"columns": [
									{
										"type": "Column",
										"width": "90px",
										"items": [
											{
												"type": "TextBlock",
												"weight": "bolder",
												"text": "[REDACTED]"
											},
											{
												"type": "TextBlock",
												"weight": "bolder",
												"text": "[REDACTED]"
											},
											{
												"type": "TextBlock",
												"weight": "bolder",
												"text": "[REDACTED]"
											},
											{
												"type": "TextBlock",
												"weight": "bolder",
												"text": "[REDACTED]"
											},
											{
												"type": "TextBlock",
												"weight": "bolder",
												"text": "[REDACTED]"
											}
										]
									},
									{
										"type": "Column",
										"items": [
											{
												"type": "TextBlock",
												"text": "[REDACTED]"
											},
											{
												"type": "TextBlock",
												"text": "[REDACTED]"
											},
											{
												"type": "TextBlock",
												"text": "[REDACTED]"
											},
											{
												"type": "TextBlock",
												"text": "[REDACTED]"
											},
											{
												"type": "TextBlock",
												"text": "[REDACTED]"
											}
										]
									}
								]
							}
						],
						"separator": true
					},
					{
						"type": "Container",
						"items": [
							{
								"type": "ColumnSet",
								"columns": [
									{
										"type": "Column",
										"width": "90px",
										"items": [
											{
												"type": "TextBlock",
												"weight": "bolder",
												"text": "[REDACTED]"
											}
										]
									},
									{
										"type": "Column",
										"items": [
											{
												"type": "Container",
												"items": [
													{
														"type": "ColumnSet",
														"columns": [
															{
																"type": "Column",
																"items": [
																	{
																		"type": "TextBlock",
																		"text": "[REDACTED]",
																		"wrap": true
																	}
																]
															},
															{
																"type": "Column",
																"items": [
																	{
																		"type": "TextBlock",
																		"id": "[REDACTED]",
																		"color": "accent",
																		"text": "[REDACTED]"
																	},
																	{
																		"type": "TextBlock",
																		"id": "[REDACTED]",
																		"color": "accent",
																		"text": "[REDACTED]",
																		"isVisible": false
																	}
																],
																"selectAction": {
																	"type": "Action.ToggleVisibility",
																	"targetElements": [
																		"[REDACTED]",
																		"[REDACTED]",
																		"[REDACTED]"
																	]
																}
															}
														]
													},
													{
														"type": "Container",
														"id": "[REDACTED]",
														"items": [
															{
																"type": "TextBlock",
																"text": "[REDACTED]",
																"wrap": true
															},
															{
																"type": "TextBlock",
																"text": "[REDACTED]",
																"wrap": true
															}
														],
														"isVisible": false
													}
												]
											}
										]
									}
								]
							}
						]
					},
					{
						"type": "TextBlock",
						"text": "[REDACTED]",
						"wrap": true,
						"maxLines": 10
					}
				],
				"actions": [
					{
						"type": "Action.ShowCard",
						"card": {
							"type": "AdaptiveCard",
							"version": "1.3",
							"actions": [
								{
									"type": "Action.OpenUrl",
									"url": "[REDACTED]",
									"title": "[REDACTED]"
								},
								{
									"type": "Action.OpenUrl",
									"url": "[REDACTED]",
									"title": "[REDACTED]"
								},
								{
									"type": "Action.OpenUrl",
									"url": "[REDACTED]",
									"title": "[REDACTED]"
								},
								{
									"type": "Action.OpenUrl",
									"url": "[REDACTED]",
									"title": "[REDACTED]"
								},
								{
									"type": "Action.OpenUrl",
									"url": "[REDACTED]",
									"title": "[REDACTED]"
								},
								{
									"type": "Action.OpenUrl",
									"url": "[REDACTED]",
									"title": "[REDACTED]"
								}
							]
						},
						"title": "[REDACTED]"
					},
					{
						"type": "Action.OpenUrl",
						"url": "[REDACTED]",
						"title": "[REDACTED]"
					},
					{
						"type": "Action.ShowCard",
						"card": {
							"type": "AdaptiveCard",
							"version": "1.3",
							"actions": [
								{
									"type": "Action.OpenUrl",
									"url": "[REDACTED]",
									"title": "[REDACTED]"
								},
								{
									"type": "Action.OpenUrl",
									"url": "[REDACTED]",
									"title": "[REDACTED]"
								},
								{
									"type": "Action.OpenUrl",
									"url": "[REDACTED]",
									"title": "[REDACTED]"
								},
								{
									"type": "Action.OpenUrl",
									"url": "[REDACTED]",
									"title": "[REDACTED]"
								},
								{
									"type": "Action.OpenUrl",
									"url": "[REDACTED]",
									"title": "[REDACTED]"
								}
							]
						},
						"title": "[REDACTED]"
					},
					{
						"type": "Action.OpenUrl",
						"url": "[REDACTED]",
						"title": "[REDACTED]"
					}
				],
				"msteams": {
					"Width": "Full"
				}
			}
		}
	]
}
```
</details>

**Comment by Meghana-MSFT** [comment]
@grietine - Thank you for sharing the JSON, we are also able to repro this issue with new channel experience in Teams. We will check this internally and get back to you. Thank you.

**Comment by CDSFounder** [comment]
@Meghana-MSFT Also want to say this "bug" is causing major frustrations for us as well. thnx

**Comment by Meghana-MSFT** [comment]
@CDSFounder - Apologies for the inconvenience caused. We have shared this feedback with team. We will keep you posted. Thank you.

**Comment by grietine** [comment]
> @CDSFounder - Apologies for the inconvenience caused. We have shared this feedback with team. We will keep you posted. Thank you.

What is the status / response from your team?

**Comment by Meghana-MSFT** [comment]
Unfortunately, we do not have any update to share. Thank you for your understanding.

**Comment by jocsch** [comment]
Can we vote anywhere to make this issue a priority? 
This is a major concern for us as well

**Comment by Meghana-MSFT** [comment]
Unfortunately, there is no such option. We are following up with the team internally. We will keep you posted. Thank you.

**Comment by Meghana-MSFT** [comment]
Fix has been made to this issue. But it hasn't reached the public rings yet. We will keep you posted.

**Comment by xmmarcotte** [comment]
@Meghana-MSFT my company is suffering from this affliction as well. Is there any kind of timeline for a fix?

**Comment by jay-staffingengine** [comment]
This is affecting us and our customers as well. Any updates on this?

**Comment by CaioNarvaez** [comment]
@Meghana-MSFT  Any update on publishing the fix? This is very disappointing to our users. I read above that the fix was made but not published yet.

**Comment by co-sic** [comment]
@Meghana-MSFT our company is also affected by this, would be nice to have this fix ASAP, since it is disrupting our workflow a lot.

**Comment by Meghana-MSFT** [comment]
Apologies for the inconvenience caused to you. Fix is going to rollout in few weeks, but we don't have any exact ETA to share.

**Comment by theamazingtik** [comment]
> Apologies for the inconvenience caused to you. Fix is going to rollout in few weeks, but we don't have any exact ETA to share.

Any updates on when Microsoft will rollout the fix?

**Comment by chinhodado** [comment]
Same issue here, very frustrating. Any ETA for the fix?

**Comment by Meghana-MSFT** [comment]
This issue is fixed in new Teams T2.1. As you can see in below screenshot, see more/less button is removed.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/4741d51a-2934-4f99-9437-5f795cafd298)

**Comment by Meghana-MSFT** [comment]
Teams T2.1 is the new version of Teams. We tested in below version of Teams.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/6cb3a319-4dcf-4f87-aae5-5e5afe1abd51)

**Comment by co-sic** [comment]
@Meghana-MSFT What about the teams web app? As a linux user i only use Teams in the Browser and i don't see the issue fixed there.

**Comment by Meghana-MSFT** [comment]
@co-sic - This issue is fixed in web client as well in the new version of Teams. Please find the version details in below screenshot. 

Version details:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/80e63fd1-7dad-4981-b460-3b6700e5132e)

No see more/less button:

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/08eb8f48-8dba-4efe-9a84-72c3ef12d01d)

**Comment by jay-staffingengine** [comment]
@Meghana-MSFT I am still seeing the issue in the version screenshotted below. 

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/74203715/a768bc64-53a3-434e-8979-681f872fed14)

**Comment by jay-staffingengine** [comment]
I’m on a PC

**Comment by jkdufair** [comment]
> @Meghana-MSFT I am still seeing the issue in the version screenshotted below.
> 
> ![image](https://private-user-images.githubusercontent.com/74203715/299453751-a768bc64-53a3-434e-8979-681f872fed14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTMzNDQsIm5iZiI6MTcwNjE5MzA0NCwicGF0aCI6Ii83NDIwMzcxNS8yOTk0NTM3NTEtYTc2OGJjNjQtNTNhMy00MzRlLTg5NzktNjgxZjg3MmZlZDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE0MzA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMjZkNTRhZmZjZDNiYWM0YWU5NjM4YTEyZWM3ZjliMjNkODE4MmNkM2NlZTg2ZWE5OGU4YzVhYmQxY2U5OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qBNVc8uSrwe5U8JCJLEhpiA1T8s-VWeRBXlK4PHdVD8)

Same problem here. Same version of Teams. Also web version still exhibits the problem. macOS Sonoma 14.1.2

**Comment by Meghana-MSFT** [comment]
We will check internally and get back to you.

**Comment by jkdufair** [comment]
Still not working. Not on the desktop client - latest version. Not on the web client. And you never got back to us.

**Comment by Meghana-MSFT** [comment]
Please note that the fix was done for adaptive cards and the original issue in this thread is also reported for adaptive cards. If you are still facing the issue with adaptive cards, then please share the card payload using the fiddler trace so that we can confirm that the Teams client is indeed getting the 'Adaptive card' type and then we can proceed from there. 

Please follow these steps -

1. Have Fiddler running/capturing network traces.
2. Like the message that contains the card:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/330ca5b0-214c-4f18-95d0-10008976fd60)
3. After you've liked the message, stop capturing and find the following in the traces:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/735d65f2-fbd0-4555-af18-e69c69e3243d)
4.Drag the network request to the Composer tab, and remove the "like" reaction from the Request Body. Remove /properties?name=emotions&replace=true from the request URL (it's at the very end), and change the method from PUT to GET. You should end up with something like this:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/5fcfb366-bc7d-44e4-83fb-67705521447c)
5. Click Execute.
6. Click on the new Request that pops up and decode the response.
7. Go to TextView and you'll see the following:
8. For Message Extension Card:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/c1e4c460-59ba-404e-97cd-8ae1782dd45d)
9. For Bot Cards
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/eab90084-08b8-4d8c-b210-0a9e3b4e46b9)
10. For Bot Cards, you will need to decode the b64 object using some site like this: https://www.base64decode.org/ . Copy everything besides the quotes of the value assigned with the Swift b64 and pasted it in the decoder. You should get something like this:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/37c9570a-7786-487b-a8e3-a0cabef04896)

**Comment by jkdufair** [comment]
This is a response going through the steps above from a card from our Azure DevOps integration that is still showing "see more":

{"sequenceId":29913,"conversationid":"19:de8dda2a58934e37ba460187e9abed3a@thread.tacv2","conversationLink":"https://amer.ng.msg.teams.microsoft.com/v1/users/ME/conversations/19:de8dda2a58934e37ba460187e9abed3a@thread.tacv2","contenttype":"text","type":"Message","s2spartnername":"SMBA","annotationsSummary":{},"hasAnnotated":true,"id":"1707935024139","clientmessageid":"1707935024003","version":"1707935414485","messagetype":"RichText/Media_Card","content":"<URIObject type=\"SWIFT.1\" url_thumbnail=\"https://urlp.asm.skype.com/v1/url/content?url=https://neu1-urlp.secure.skypeassets.com/static/card-128x128.png\">Build 20240214.6 - succeeded<Title>Build 20240214.6 - succeeded</Title><Swift b64=\"eyJ0eXBlIjoibWVzc2FnZSIsInN1bW1hcnkiOiJCdWlsZCAyMDI0MDIxNC42IC0gc3VjY2VlZGVkIiwidGV4dEZvcm1hdCI6Im1hcmtkb3duIiwiYXR0YWNobWVudHMiOlt7ImNvbnRlbnQiOnsic3VtbWFyeSI6IkJ1aWxkIDIwMjQwMjE0LjYgLSBzdWNjZWVkZWQiLCJ0aGVtZUNvbG9yIjoiIzEwN2MxMCIsInNlY3Rpb25zIjpbeyJ0ZXh0IjoiPHA+QnVpbGQgZm9yIDxpbWcgc3JjPVwiaHR0cHM6Ly91cy1wcm9kLmFzeW5jZ3cudGVhbXMubWljcm9zb2Z0LmNvbS91cmxwL3YxL3VybC9jb250ZW50P3VybD1odHRwcyUzYSUyZiUyZmNkbi52c2Fzc2V0cy5pbyUyZmNvbnRlbnQlMmZub3RpZmljYXRpb25zJTJmdGVhbXMtcHVzaHJlcG8ucG5nXCIgYWx0PVwiUmVwbyBJY29uXCI+IDxhPjwvYT4gPGltZyBzcmM9XCJodHRwczovL3VzLXByb2QuYXN5bmNndy50ZWFtcy5taWNyb3NvZnQuY29tL3VybHAvdjEvdXJsL2NvbnRlbnQ/dXJsPWh0dHBzJTNhJTJmJTJmY2RuLnZzYXNzZXRzLmlvJTJmY29udGVudCUyZm5vdGlmaWNhdGlvbnMlMmZ0ZWFtcy1icmFuY2gucG5nXCIgYWx0PVwiQnJhbmNoIEljb25cIj4gPGEgaHJlZj1cIi8jdmVyc2lvbj1HQm1haW5cIj5tYWluPC9hPiwgZmluaXNoZWQgMDIvMTQvMjAyNCAxODoyMzozMCBVVEM8L3A+IiwiYWN0aXZpdHlUaXRsZSI6IjxwPjxhIGhyZWY9XCJodHRwczovL2Rldi5henVyZS5jb20vaXRhcC1pbmZvcm1hdGljcy1henVyZS82MDlhOTU3Ni1kYjM2LTQyZmUtYjJmYS02MWI2OGE4MDg3ZTAvX2J1aWxkL3Jlc3VsdHM/YnVpbGRJZD0xMzY3N1wiPkRFViBSZWxlYXNlIC8gMjAyNDAyMTQuNjwvYT4gKFN1Y2NlZWRlZCk8L3A+IiwiYWN0aXZpdHlTdWJ0aXRsZSI6IjxwPlRyaWdnZXI6IG1hbnVhbCBmb3IgV2lsbCBHcmF1dm9nZWw8L3A+IiwiYWN0aXZpdHlJbWFnZSI6Imh0dHBzOi8vdXMtcHJvZC5hc3luY2d3LnRlYW1zLm1pY3Jvc29mdC5jb20vdXJscC92MS91cmwvY29udGVudD91cmw9aHR0cHMlM2ElMmYlMmZjZG4udnNhc3NldHMuaW8lMmZjb250ZW50JTJmbm90aWZpY2F0aW9ucyUyZnRlYW1zLWJ1aWxkLXN1Y2NlZWRlZC5wbmciLCJhY3Rpdml0eUltYWdlVHlwZSI6ImFydGljbGUiLCJtYXJrZG93biI6dHJ1ZSwic3RhcnRHcm91cCI6ZmFsc2V9XSwicG90ZW50aWFsQWN0aW9uIjpbXX0sImNvbnRlbnRUeXBlIjoiYXBwbGljYXRpb24vdm5kLm1pY3Jvc29mdC50ZWFtcy5jYXJkLm8zNjVjb25uZWN0b3IifV19\" /><Description /></URIObject>","from":"https://amer.ng.msg.teams.microsoft.com/v1/users/ME/contacts/28:integration:bxi61rx48u","fromTenantId":"4130bd39-7c53-419c-b1e5-8758d6d63f21","imdisplayname":"Azure DevOps","composetime":"2024-02-14T18:23:44.1390000Z","originalarrivaltime":"2024-02-14T18:23:44.1390000Z","properties":{"meta":"{\"connectorSenderGuid\":\"dd63c2fc-4ea3-491a-9e74-fcc31f346478\",\"providerAccountUniqueId\":\"ddadc0c6-be28-601f-b39d-40a1dda7e279\",\"connectorConfigurationAlternateId\":\"496c81a294b94bfd87832bbc1c8a9095\"}","s2spartnername":"SMBA","emotions":[{"key":"like","users":[]}]}}%

And decoding the Base64 data:

{"type":"message","summary":"Build 20240214.6 - succeeded","textFormat":"markdown","attachments":[{"content":{"summary":"Build 20240214.6 - succeeded","themeColor":"#107c10","sections":[{"text":"<p>Build for <img src=\"https://us-prod.asyncgw.teams.microsoft.com/urlp/v1/url/content?url=https%3a%2f%2fcdn.vsassets.io%2fcontent%2fnotifications%2fteams-pushrepo.png\" alt=\"Repo Icon\"> <a></a> <img src=\"https://us-prod.asyncgw.teams.microsoft.com/urlp/v1/url/content?url=https%3a%2f%2fcdn.vsassets.io%2fcontent%2fnotifications%2fteams-branch.png\" alt=\"Branch Icon\"> <a href=\"/#version=GBmain\">main</a>, finished 02/14/2024 18:23:30 UTC</p>","activityTitle":"<p><a href=\"https://dev.azure.com/itap-informatics-azure/609a9576-db36-42fe-b2fa-61b68a8087e0/_build/results?buildId=13677\">DEV Release / 20240214.6</a> (Succeeded)</p>","activitySubtitle":"<p>Trigger: manual for Will Grauvogel</p>","activityImage":"https://us-prod.asyncgw.teams.microsoft.com/urlp/v1/url/content?url=https%3a%2f%2fcdn.vsassets.io%2fcontent%2fnotifications%2fteams-build-succeeded.png","activityImageType":"article","markdown":true,"startGroup":false}],"potentialAction":[]},"contentType":"application/vnd.microsoft.teams.card.o365connector"}]}%

**Comment by Meghana-MSFT** [comment]
As we can see from the payload (see the contentType value at the end) it's a o365connector card as suspected and not an Adaptive card which is why you're seeing the 'see more'. Anyway, even for O365 connector cards, compared to Teams classic, the card was being truncated at much shorter height in latest Teams so, engineering team has pushed a change to bring parity with classic Teams and based on Teams releases, looks like that change will take some time to reach the general ring.

**Comment by waciii-rtp-nc** [comment]
We are no longer able to avoid leaving Teams Classic and now are gravely afflicted by this for many integrations.  It's near crippling with respect to something that used to be so seamless and useful

Version 24004.1304.2655.7488 (24004.1304.2655.7488)

When we set up our Integrations we started trying to use Adaptive Cards, but were unable and had to use https://learn.microsoft.com/en-us/outlook/actionable-messages/message-card-reference for Jira -> Teams Connector Webhooks Cards and for Webhooks sent directly from CI/CD Code

Please do one or all of the following:
- If these Legacy Message Cards are different from o365connector cards, please add Legacy Message Card as another case that needs to be addressed
- Please suggest an alternative relief.  I'm not sure if we could get off Legacy Message Cards but if you could suggest how it would be welcomed

It so discouraging having something so useful working and an escape like this ruin it

**Comment by tocaleb** [comment]
The initial comment on this thread highlights a broader concern. 

Rather than imposing clutter and making unilateral decisions on behalf of users, could you instead implement configuration options to customize the display size and behavior of the 'see more/less' feature?

This has crippled our integrations and general experience with Teams.

**Comment by waciii-rtp-nc** [comment]
@Meghana-MSFT 

Please provide an update on when this issue might be solved in all the venues it remains broken.  I was able to review to Teams Classic for awhile but now that option has been taken from me.

This is so painful for something that worked so seemlessly.

**Comment by matthdonnet** [comment]
Same issue. You just broke an app that we took months to build. You seriously degraded the user experience for us. New ms teams is not fixed....
